### ISSUE TITLE
Page reload does not recognise new containment

### ISSUE THREAD

**Issue by mingsterism** [anseki/plain-draggable#10]
Hi, 
Amazing work with this library. thanks for your efforts. 
Currently I'm running this code.
https://hastebin.com/munofofuba.xml
However, the containment does not seem to recognize my parent height. I need to adjust my size window before it recognises the height. then dragging works. 
Thanks

**Comment by mingsterism** [comment]
Got it fixed. Silly mistake of not placing css and script tags in right order.

**Comment by anseki** [comment]
:smile:
