### ISSUE TITLE
Help with unbounded element

### ISSUE THREAD

**Issue by Stanteq** [anseki/plain-draggable#101]
Hi, I really appreciate this script. 
All examples are bounded by a container but there is a way to make a draggable element unbounded? To be able to move the element "infinitely" over the borders. Thank you.

for example: https://jerosoler.github.io/Drawflow/

**Comment by anseki** [comment]
Hi @Stanteq, thank you for the comment.
You can specify [`containment`](https://anseki.github.io/plain-draggable/#options-containment) option.

**Comment by Stanteq** [comment]
> Hi @Stanteq, thank you for the comment.
> You can specify [`containment`](https://anseki.github.io/plain-draggable/#options-containment) option.

With the containment the draggable block will stop on the borders (in case of missing it will take the parent one) but what i want is to drag outside the borders.

**Comment by anseki** [comment]
Sorry, do you mean that specifying `<body>` element for the `containment` option didn't work?

**Comment by Stanteq** [comment]
> Sorry, do you mean that specifying `<body>` element for the `containment` option didn't work?

```
 new PlainDraggable(document.getElementById('target'), {
    containment: document.getElementsByTagName('body')[0],
});
```

Oviously it works and the block stops at the edge of the body (containment). What I want to achieve is to go outside of the containment. Imagine if you want to create a draw flow of infinite space which dont need a containment to limit this space.

**Comment by anseki** [comment]
Hmm... I can't understand that...
Try this:
```js
new PlainDraggable(document.getElementById('target'), {
  containment: {left: '-50%', top: '-50%', right: '150%', bottom: '150%'}
});
```
Maybe this is meaningless because mouse pointer can't be caught outside of document.

**Comment by Stanteq** [comment]
Your solution can solve like a part of the problem. 

Imagine you have a big draggable box and you move it arround. Maybe half of it can stay outside of the "visible" screen because you have a containment left: -50% etc. but not an infinite in case you move the containment to see the hidden part of the draggable blocks and drag it again (like in this example https://jerosoler.github.io/Drawflow/). Maybe a solution (new feature) is to have a flag to decide if the draggable blocks should stay in the containment or not.

**Comment by anseki** [comment]
Hmm... Sorry, I couldn't understand what you want to do.
Anyway, this library is unsuitable for your app. You had better use another library that is suitable for your app.

**Comment by Stanteq** [comment]
> Hmm... Sorry, I couldn't understand what you want to do.
> Anyway, this library is unsuitable for your app. You had better use another library that is suitable for your app.

Fixed it by comenting this function:

```
 function fix() {
    if (props.minLeft >= props.maxLeft) { // Disabled
      position.left = elementBBox.left;
    } else if (position.left < props.minLeft) {
      position.left = props.minLeft;
    } else if (position.left > props.maxLeft) {
      position.left = props.maxLeft;
    }
    if (props.minTop >= props.maxTop) { // Disabled
      position.top = elementBBox.top;
    } else if (position.top < props.minTop) {
      position.top = props.minTop;
    } else if (position.top > props.maxTop) {
      position.top = props.maxTop;
    }
  }
```

As a side effect it not working anymore the snap features in case if it is outside the containment.

**Comment by anseki** [comment]
I see. :smile:
