### ISSUE TITLE
Bad position when some ancestor is scaled

### ISSUE THREAD

**Issue by ogadaki** [anseki/plain-draggable#105]
If some parent is scaled using CSS, the position of the draggable during dragging isn't the mouse position. For example with a scale of 0.5 the moving distance of the draggable is half the one of the mouse.

Code example:

``` html
<div
  style="
    width: 600px; height: 600px; padding: 10px; background-color: #eeeeee;
    transform: scale(0.5);
  "
>
  <div id="draggable" style="padding: 20px; width: 100px; background-color: white;">
    drag me
  </div>
</div>
```

``` javascript
const draggable = new PlainDraggable(document.getElementById('draggable'))
```

**Comment by anseki** [comment]
Hi @ogadaki, thank you for the comment.
This may help you: https://github.com/anseki/plain-draggable/issues/13

**Comment by ogadaki** [comment]
Hi @aneski, thanks for your quick reply, I'll take a look.

For a bit of context, I saw this while combining PlainDraggable with [panzzom](https://github.com/anvaka/panzoom).

And I forgot an important point from my initial message: thanks a lot for your work! I'm just starting to use it but, from what I'm reading, this tool (and others like LeaderLine) will be very useful to me.

**Comment by anseki** [comment]
I'm glad if  I could help you. :smile: 
Could you close this issue if it is solved?
