### ISSUE TITLE
Moving with keyboard and mouse

### ISSUE THREAD

**Issue by jersict** [anseki/plain-draggable#106]
Hello.

I have an issue, when I would like to enable moving the draggable items with keyboard as well as the mouse. I am currently trying to change the css transform translate, upon keydown events, but the issue is that, somehow the position of the element changes back to the previous position, when I try to drag it with the mouse. 
Do you have any suggestion on how to fix this, or even another solution that would help me in enabling dragging with mouse and keyboard?

Thank you for the script, it has been a great help

**Comment by anseki** [comment]
Hi @jersict, thank you for the comment.
By default, PlainDraggable uses the `translate` CSS function to move the draggable element. And your code too. That is, these are conflict.
You can use [`left` and `top`](https://anseki.github.io/plain-draggable/#options-left_top) to move the draggable element instead of the `translate`.

**Comment by anseki** [comment]
Of course you can get current position also via the `left` and `top` options.
For example, this code moves it rightward from current position:
```js
draggable.left += 10;
```
So, could you close this issue if it was solved?

**Comment by jersict** [comment]
I currently have the problem that I haven't managed yet to change `left` or `down` of the previously existing draggable divs. If I try to use `document.getElementById(id)`, `left` and `top` are not defined, but if I do `new PlainDraggable(document.getElementById(id));` it creates another draggable element, and I have more and more.

**Comment by anseki** [comment]
The `left` and `top` are defined when you do `new PlainDraggable()`.
You don't have to create another instance.

**Comment by jersict** [comment]
Okay, I found a solution, which is probably not the best, but it works for now. 
I saved the `draggable` in a map, from which I can get it, when I need to move the object. 
If you have a better solution please do share it I would love to know, but for now I will close this issue.

**Comment by anseki** [comment]
I see.
You have to get an instance to access to properties, methods, etc. of the class object.
For example:
```js
// Get new instance.
const draggable = new PlainDraggable(document.getElementById('target'));
// Access and change the property of the instance.
draggable.left += 10;
// And you can do something with this object via this variable that is named `draggable` as the instance.
```
These are specifications of Object Oriented Programming, not JavaScript.
