### ISSUE TITLE
How to use it with react ?

### ISSUE THREAD

**Issue by satheesh66** [anseki/plain-draggable#108]
I am unable to use it with react, @anseki can u help me with this

**Comment by anseki** [comment]
Hi @satheesh66, thank you for the comment.
Could you explain that?

**Comment by satheesh66** [comment]
I am trying to import plain-draggable with my react component but I can't initialize like 

import PlainDraggable from 'plain-draggable';
let draggable = new PlainDraggable();

I am getting errors like this
Error: plain_draggable_1.default is not a constructor

**Comment by anseki** [comment]
Was another error thrown?

**Comment by satheesh66** [comment]
> Was another error thrown?

no

**Comment by anseki** [comment]
Maybe your Webpack script is wrong if another error wan't thrown.
You have to import the library from `plain-draggable.esm.js` file.

**Comment by ashvin777** [comment]
Here is the sample which you can use to create a React component very easily from the JS library and use it in your React project 

Live Demo - [https://jsitor.com/tAy-tniLI](https://jsitor.com/tAy-tniLI )

```javascript
import React, { useRef, useEffect } from 'react';
import ReactDOM from 'react-dom';
import Draggable from 'plain-draggable';

function PlainDraggableComponent({ children, draggableProps, ...rest }) {
  const node = useRef();

  useEffect(() => {
    const el1 = node.current;
    new Draggable(el1, draggableProps);
  }, [node]);

  return (
    <div ref={node} {...rest}>{children}</div>
  )
}

function App() {
  return (
    <div className="app">
      <PlainDraggableComponent
        className="node"
        draggableProps={{
          left: 100,
          top: 200
        }}>
        <div>Drag Me!</div>
      </PlainDraggableComponent>
    </div>
  );
}

ReactDOM.render(
  <App />,
  document.getElementById('container')
);
```

**Comment by anseki** [comment]
Hi @ashvin777, thank you for the information. :smile: :+1:

**Comment by ashvin777** [comment]
Thanks to you for building this amazing lib, I like both LeaderLine and PlainDraggable. I am planning to use these to build the tool like node-red. If there is any suggestion or thoughts then please advise 😊.

**Comment by anseki** [comment]
Those libraries are used for flowchart, logic tree, organization chart, entity relationship diagram, etc.
You can make an issue if you have question.

**Comment by satheesh66** [comment]
Issue resolved thankyou @anseki and @ashvin777

**Comment by anseki** [comment]
:smile:
