### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by David-Carty** [anseki/plain-draggable#109]
Hey, great functionality.  However, I am struggling to maintain containment when I make the div resizable?  In short, I need drag, resize and containment functionality.  Thanks in advance, David.

**Comment by anseki** [comment]
Hi @David-Carty, thank you for the comment.
You have to call [`position`](https://anseki.github.io/plain-draggable/#position) method if you changed the layout.

**Comment by David-Carty** [comment]
Hi Anseki,  thanks for the quick response.  I did notice the position method.  Don't know if it will solve my issue.  Let me try and explain a little better.  In this fiddle:

https://jsfiddle.net/xhLdr03a/1/

I have the resize and containment working, but I also want to drag the blue box whilst still containing it.  Is there any way to have the combination of drag, resize and containment?  Thanks in advance David

**Comment by anseki** [comment]
I see.
Try this: https://jsfiddle.net/etwyb3sm/

**Comment by David-Carty** [comment]
Hi Anseki, thanks for that.  Looks great. David

**Comment by anseki** [comment]
:smile:
