### ISSUE TITLE
Multiple items

### ISSUE THREAD

**Issue by szybki8562** [anseki/plain-draggable#11]
Hello 
There is a possibility to add array items or dynamically (multiple) to snap targets?

**Comment by anseki** [comment]
Hi @szybki8562, thank you for the comment.
Yes of course you can change options including the `snap` dynamically.

**Comment by szybki8562** [comment]
can u help me how ? im new in js
THX

**Comment by anseki** [comment]
For example:
https://jsfiddle.net/yjmhdr2a/

**Comment by szybki8562** [comment]
thanks for the answer, but it was not what I was talking about

I have random id elements added while the application is running. I asked if it can be added to the current snap or from whole array svg

**Comment by anseki** [comment]
It seems that the example is what you want.
You can specify snap targets even if those have random IDs.
See line 4.

**Comment by szybki8562** [comment]
i cant write this way

`draggable.snap = [
    **_document.getElementById('box-a'),
    document.getElementById('box-b')_**
  ];`

i dont have this elements at start and i dont know what will the id
elements that I want to attract, adds to the array with time

**Comment by anseki** [comment]
I merged the example and your code:
https://jsfiddle.net/yjmhdr2a/1/
BTW, the `TEMPARRAY` and `gravity` option are not needed.

**Comment by szybki8562** [comment]
`ARRAY = [{id: 'box-a'}, {id: 'box-b'}];
    
    var TEMPARRAY = ARRAY.map(function(target) { return document.getElementById(target.id);});

    alert(TEMPARRAY);`

in my proj alert is null in jsfiddle OK

**Comment by anseki** [comment]
Sorry, my English is poor.
What do you mean?

**Comment by szybki8562** [comment]
TEMPARRAY  have empty

**Comment by anseki** [comment]
Did you try this?
https://jsfiddle.net/yjmhdr2a/2/

**Comment by szybki8562** [comment]
ARRAY.map propably this not working

**Comment by szybki8562** [comment]
something is wrong with my project your fiddle is OK

THX for yr time

**Comment by anseki** [comment]
The `null` is different from "empty".
You should clear up that.
If that is "empty", the `getElementById` couldn't get elements.
If that is `null`, your code has problem.

**Comment by szybki8562** [comment]
i have comma

**Comment by anseki** [comment]
For example:

```js
var ARRAY = [{id: 'box-a'}, {id: 'box-b'}],
  TEMPARRAY = ARRAY.map(function(target) { return document.getElementById(target.id); });
```

This code gets elements `box-a` and `box-b`.
In other words, that gets nothing if there are not `box-a` and `box-b`.

**Comment by anseki** [comment]
What is "comma"?

**Comment by szybki8562** [comment]
,

**Comment by anseki** [comment]
I know "comma".
What do you mean "i have comma"?

**Comment by szybki8562** [comment]
array.map return only comma in alert before map is ok have values

**Comment by anseki** [comment]
Please don't change comments that were read because we can't have conversation.
So, could you explain the current progress?

**Comment by szybki8562** [comment]
I have no value after the array map

**Comment by anseki** [comment]
In console, try this:
```js
document.getElementById('box-a')
```

**Comment by szybki8562** [comment]
array map needs some library?

**Comment by anseki** [comment]
What is your environment? browser and version?

**Comment by szybki8562** [comment]
vs code  jquery 3.3.1 opera

**Comment by anseki** [comment]
Which version of Opera?

**Comment by szybki8562** [comment]
pure html with <script/> same result

opera new
chrome and firefox developer same result

**Comment by szybki8562** [comment]
opera 56.0.3051.36

**Comment by anseki** [comment]
I see. The `Array#map` in your environment doesn't need a library because ECMAScript 5 supports that.

So, did you that?
https://github.com/anseki/plain-draggable/issues/11#issuecomment-429697715

**Comment by szybki8562** [comment]
where?

**Comment by anseki** [comment]
Try this in console of browser:
https://github.com/anseki/plain-draggable/issues/11#issuecomment-429697715

**Comment by szybki8562** [comment]
var numbers = [4, 9, 16, 25];
alert(numbers.map(Math.sqrt));

this map ok

**Comment by anseki** [comment]
Yes, of course I know.
So, did you try the code that I indicated?

**Comment by szybki8562** [comment]
document.getElementById('box-a') ?

**Comment by anseki** [comment]
Yes.

**Comment by szybki8562** [comment]
i dont know how in console this 'document.getElementById('box-a')' must be a return of one value

**Comment by szybki8562** [comment]
`ARRAY.map(function(target) {
       alert(target.id); OK
    });

ARRAY.map(function(target) {
       alert(document.getElementById(target.id)); NO OK
    });
`

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that you don't know how to execute the code in console?

**Comment by szybki8562** [comment]
return null

**Comment by anseki** [comment]
?

**Comment by szybki8562** [comment]
i dont have that element i only check array draggable working

**Comment by anseki** [comment]
Do you mean that this code returned `null`?
```js
document.getElementById('box-a')
```

**Comment by szybki8562** [comment]
yes i dont have element with box-a id

**Comment by szybki8562** [comment]
ok i understand im very sleepy sorry for my bad

**Comment by szybki8562** [comment]
i got null or nothing because i wanted getelement

**Comment by anseki** [comment]
I see.
Your code has problem.
Did you read this?
https://github.com/anseki/plain-draggable/issues/11#issuecomment-429694673

**Comment by anseki** [comment]
You must specify correct ID to both ID of the element and `getElementById`.

**Comment by szybki8562** [comment]
hehe did not pay attention to getElementById when i delete this then ok

**Comment by szybki8562** [comment]
yes my id's have in another array

**Comment by szybki8562** [comment]
for (var it in WALLS) {
        ARRAY.push([{id: WALLS[it].id}]);
    }

but this not working

**Comment by anseki** [comment]
Try this:
```js
console.log(ARRAY);
```

**Comment by szybki8562** [comment]
in console have value

**Comment by anseki** [comment]
What value?

**Comment by szybki8562** [comment]
my id and some another values in json propably

**Comment by anseki** [comment]
What ID?

**Comment by szybki8562** [comment]
from my loop elements

**Comment by szybki8562** [comment]
but TEMPARRAY length = 0

**Comment by anseki** [comment]
What ID?
Could you tell me that?

**Comment by szybki8562** [comment]
"2WITS" this is id. and i want this id assign to draggable

**Comment by anseki** [comment]
Ok, try this:
```js
document.getElementById('2WITS')
```

**Comment by szybki8562** [comment]
return my svg path

**Comment by szybki8562** [comment]
<path d="M750,310 L730,290 L730,440 L750,420 Zi" stroke="none" fill="#666" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" fill-rule="nonzero" id="2WITS"></path>

**Comment by szybki8562** [comment]
`<path d="M750,310 L730,290 L730,440 L750,420 Zi" stroke="none" fill="#666" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" fill-rule="nonzero" id="2WITS"></path>`

**Comment by anseki** [comment]
I see.
It seems that the ID or your code is obviously wrong.
At least, when the draggable is constructed, the `2WITS` element doesn't exist yet.

**Comment by anseki** [comment]
You can add snap target after that element was added.
Before the element is added, of course you can't.
This is JavaScript, not PlainDraggable.
See: https://github.com/anseki/plain-draggable/issues/11#issuecomment-429694673

**Comment by szybki8562** [comment]
i have elements.
add element -> add to array -> array to plaindraggable
from the beginning

no elements no array

**Comment by anseki** [comment]
You must make the `TEMPARRAY` after the elements were added.

**Comment by szybki8562** [comment]
yes

**Comment by szybki8562** [comment]
but TEMPARRAY is null as image
https://github.com/anseki/plain-draggable/issues/11#issuecomment-429704608

**Comment by anseki** [comment]
The `null` that returned by `getElementById` means that the element doesn't exist.

**Comment by szybki8562** [comment]
there are elements for sure

**Comment by anseki** [comment]
This works fine:
https://jsfiddle.net/yjmhdr2a/2/
Because the elements exist.

**Comment by anseki** [comment]
For test, insert this line in to your code, before `ARRAY.map`.

```js
console.log('2WITS: ' + document.getElementById('2WITS'));
```

**Comment by szybki8562** [comment]
GUH23: [object SVGPathElement]

**Comment by szybki8562** [comment]
![image](https://user-images.githubusercontent.com/12680909/46930486-2f9e6d00-d046-11e8-8613-48816fc626ae.png)

**Comment by anseki** [comment]
I see, replace this:

```js
ARRAY.map(function(target) { return document.getElementById(target.id); }
```

with:
```js
ARRAY.map(function(target) { console.log(target.id + ': ' + document.getElementById(target.id)); return document.getElementById(target.id); }
```

**Comment by szybki8562** [comment]
undefined: null

**Comment by anseki** [comment]
That means the `ARRAY` is incorrect.

**Comment by szybki8562** [comment]
`for (var it in WALLS) {
         ARRAY.push([{id: WALLS[it].id}]);
 }`
this is wrong


added id by hand is ok

**Comment by anseki** [comment]
Insert this before `for (var it in WALLS) ...`:
```js
console.log(WALLS);
```

**Comment by szybki8562** [comment]
ok got 5 elements

**Comment by anseki** [comment]
What was shown?

**Comment by szybki8562** [comment]
`ARRAY.push([{id: WALLS[it].id}]);` This is fine?

**Comment by anseki** [comment]
What was shown by `console.log(WALLS);`?

**Comment by szybki8562** [comment]
![image](https://user-images.githubusercontent.com/12680909/46930926-ed2a5f80-d048-11e8-9b68-dd90718b9a76.png)

**Comment by anseki** [comment]
Click the left of `0`.

**Comment by szybki8562** [comment]
![image](https://user-images.githubusercontent.com/12680909/46931146-2d3e1200-d04a-11e8-80cc-ea9e48d05552.png)

**Comment by anseki** [comment]
Ah, ok.

Replace this:

```js
for (var it in WALLS) { ARRAY.push([{id: WALLS[it].id}]); }
```

with:

```js
for (var it in WALLS) { console.log(WALLS[it].id + ': ' + document.getElementById(WALLS[it].id)); ARRAY.push([{id: WALLS[it].id}]); }
```

**Comment by szybki8562** [comment]
![image](https://user-images.githubusercontent.com/12680909/46931202-80b06000-d04a-11e8-9138-f3007e490b77.png)

**Comment by szybki8562** [comment]
https://www.w3schools.com/js/tryit.asp?filename=tryjs_array_object

GREAT THANKS FOR HELP

**Comment by anseki** [comment]
The both `for` and `ARRAY.push` are not needed.

**Comment by szybki8562** [comment]
Everything working

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue?

**Comment by szybki8562** [comment]
YES Thanks

**Comment by anseki** [comment]
Could you close this issue if it was solved?
