### ISSUE TITLE
How to get the snap element

### ISSUE THREAD

**Issue by obonyojimmy** [anseki/plain-draggable#111]
Suppose i have a draggable instance with multiple snap targets (html targets) , how to i get to know which element was snapped , currently we only get a boolean value `snapped` but that's not very useful for this scenario. Thanks , great plugin !

**Comment by anseki** [comment]
Hi @obonyojimmy, thank you for the comment.
These may help you:
https://github.com/anseki/plain-draggable/issues/78#issuecomment-881807380
https://github.com/anseki/plain-draggable/issues/26#issuecomment-484473034

**Comment by obonyojimmy** [comment]
Thanks, 🙏 that was more than helpful.

**Comment by anseki** [comment]
:smile:
