### ISSUE TITLE
Dynamically increase height of container

### ISSUE THREAD

**Issue by Zander1983** [anseki/plain-draggable#115]
I have an app to allow users to draw polygons on scatter plots and create a tree of plots. e.g.
![Screenshot 2022-08-18 at 08 04 40](https://user-images.githubusercontent.com/996960/185327537-c4af8bcf-2e93-4992-b26f-f8a708e50721.png)

The problem I have is when a user creates 4 or more plots, they get stacked on top of each other as there is no room, and so I need to allow the user to increase the size of the container by dragging. Heres the problem:

![Screenshot 2022-08-18 at 08 06 25](https://user-images.githubusercontent.com/996960/185328532-bb9b831f-3138-4949-8f14-eb0e17b81dcd.png)

Heres the HTML:

```
      <div
      >
        <div
          id="workspace-container"
          style={{
            height: 350 + maxTop,
          }}
        >
        Here are the Draggables
        </div>
        <div
          id="dragger-container"
          style={{
            height: "5px",
            backgroundColor: "#333",
          }}
          onMouseDown={(e) => {

          }}
          onMouseMove={(e) => {
            console.log("in mouse move, e.clientY is ", e.clientY);

            let workspaceContainer = document.getElementById(
              "workspace-container"
            );

            // 480 is the original height of dragger-container from the top of the window
            // 355 is the original height of workspace-container            
            let newHeight = e.clientY - 480 + 355;
            workspaceContainer.style.height = newHeight + "px";
          }}
          onMouseUp={(e) => {
     
          }}
        ></div>
    </div>
```

When I move the mouse over `dragger-container` the height of `workspace-container` is indeed dynamically increased. However I still cannot drag the Draggables down. It seems they dont know the height of the `workspace-container` has increased.

![Screenshot 2022-08-18 at 08 14 03](https://user-images.githubusercontent.com/996960/185332851-375c48e8-685c-45e9-acd4-198917ed8cc7.png)

It may be something to do with the containment option here https://anseki.github.io/plain-draggable/#options-containment. But Im not sure....

**Comment by anseki** [comment]
Hi @Zander1983, thank you for the comment.
Sorry, my English is poor.
Do you mean that the draggable element doesn't work correctly after the size of the element was changed?
If so, you have to call [`position`](https://anseki.github.io/plain-draggable/#position) method.

**Comment by anseki** [comment]
[bot] No reply came, then this abandoned issue is closed.

**Comment by Zander1983** [comment]
Sorry for my late reply - you were correct, that fixed it.

**Comment by anseki** [comment]
:smile:
