### ISSUE TITLE
How to control the ghost shadow when dragging?

### ISSUE THREAD

**Issue by cookiejest** [anseki/plain-draggable#116]
I am trying to find how the ghost image is set when dragging an element.
 I was searching for setDragImage or something similar, any ideas?

**Comment by anseki** [comment]
Hi @cookiejest, thank you for the comment.
We don't know the "ghost shadow" and the "ghost image" that you said.
If you want to change the style of the element according to status of dragging, you can do that very easy.
For example:
https://anseki.github.io/plain-draggable/#ex-110-stage

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
