### ISSUE TITLE
Incorporate PlainDraggable to current drag events

### ISSUE THREAD

**Issue by rdimaunahan** [anseki/plain-draggable#118]
Hi aneski, I am trying to incorporate PlainDraggable into current drag events in my program since I need the snap function of the library. It is resulting to blocking the current drag events and not being able to store the current xpositon and yposition of the element after the dragend and drag. is there a way to incorporate PlainDraggeble to current drag events properly?

**Comment by anseki** [comment]
Hi @rdimaunahan, thank you for the comment.
Sorry, my English is poor. I couldn't understand your words.
The library fires the events properly and those events are blocked by nothing if you don't block those.
Does the "current drag events" that you said mean native `DragEvent` that is `Event` in DOM API?

**Comment by rdimaunahan** [comment]
Solution found by using disabled properties

**Comment by anseki** [comment]
Ok :smile:
