### ISSUE TITLE
ERROR in ./node_modules/_plain-draggable@2.5.14@plain-draggable/plain-draggable.esm.js 51:0-38

### ISSUE THREAD

**Issue by Alduin-Y** [anseki/plain-draggable#123]
Module not found: Error: Can't resolve 'm-class-list' in 'E:\ProjectDocuments\nb\line\node_modules\_plain-draggable@2.5.14@plain-draggable'

I don't know how to solve it ...XD

**Comment by anseki** [comment]
Hi @Alduin-Y, thank you for the comment.
I don't know it too because it is a terrible lack of information.
What do you want to do?
What did you do?
When the error was thrown?
etc.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
