### ISSUE TITLE
Draggable node recalculate css when scrolling browser window

### ISSUE THREAD

**Issue by Zander1983** [anseki/plain-draggable#124]
This is an amazing library and is doing a great job for me. 

One issue Im having is that as I scroll in the browser, the library changes some of the draggable nodes' CSS. For example:

this looks good:
![2022-11-29_13-15-16 (1)](https://user-images.githubusercontent.com/996960/204539532-6f6b1373-b64d-4d5d-bd87-16c61a9a2a68.png)

now when i scroll down in the browser, the library recalculates and adds a height attribute to the draggable node:

![2022-11-29_13-17-02](https://user-images.githubusercontent.com/996960/204539696-244f2948-4cfa-4ab5-ab83-f3da2a86da84.png)

Is there some way to prevent this?

**Comment by anseki** [comment]
Hi @Zander1983, thank you for the comment.
Do you mean that the `height` CSS property was changed by the library?
I don't know that issue till now.
To reproduce that, could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by Zander1983** [comment]
Yes the height CSS property, I will try to reproduce in Jsfidddle but my app is super complex so not easy

**Comment by Zander1983** [comment]
Okay proving very hard to reproduce on jsfiddle. Can you think of any reason with the properties would change on the draggable node as ai scroll? They dont always change, but sometimes the `transform`, `height` and `width` property do...

**Comment by anseki** [comment]
Sorry, I don't know the "ai scroll".
I don't know that issue till now. And it has never been reported yet.
Also, many PlainDraggable instances in this page (https://anseki.github.io/plain-draggable/) work fine without changing layout of something.
Anyway, I might find something if you can reproduce that for me.

**Comment by Zander1983** [comment]
OK I will go through your lib at the weekend and report back, please leave this issue open til then

**Comment by anseki** [comment]
Yes, of course that is needed because PlainDraggable has to re-calculate the position.
Why did you think that the `bBox.height` affects the layout of your page?

**Comment by Zander1983** [comment]
Why does it need to recalculate position on scroll of the browser window though? I could understand on scroll of the wrapper around the nodes, however not the browser window...

Ya, IM going to look into why the height is wrong. I have the height set on an inner div, not that outer node itself. That may fix it. Will report back.

**Comment by anseki** [comment]
> Why does it need to recalculate position on scroll of the browser window though?

For example, when it gets `clientX/Y` (for browser compatibility), it has to calculate the position (document base) from view port coordinates. That is, scroll value has to be added to those.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
