### ISSUE TITLE
Horizontal sliding tabs

### ISSUE THREAD

**Issue by Sharlaan** [anseki/plain-draggable#128]
Hello @anseki  awesome job with this lib 👏 

I'm willing to provide an example of horizontal dragging (like with browsers tabs), reproducing the example 230 (vertically stacked elements) from the official page.

Here is my WIP @ Codesandbox : https://codesandbox.io/s/horizontal-draggable-tabs-plain-draggable-corttc?file=/index.js

I have mostly 3 problems:
1. containement right bound does not seem to work ? (left bound is OK)
2. i want snapping to occurs when half of the dragging tab crosses half of the hovered tab, but somehow my offset calculations seem wrong ?
3. on pointer release, swapping does not occur ?

Can you help please ?

Thanks in advance !

PS: feel free to use this codesandbox in your official site ;)

**Comment by anseki** [comment]
Hi @Sharlaan, thank you for the comment.
Sorry, your code is difficult for me, then I couldn't understand that well.
Anyway, the example in the document is very simple. You can read that in the source code.
Also, you seem to be mistaking some options `snap`, `onDrag`, etc. For example, you should specify length of each tab for `step`.
Please read document more for the options.

**Comment by Sharlaan** [comment]
I inspected official site code and "simply"  reused code from devTools:
![image](https://user-images.githubusercontent.com/2692027/213993845-1587f7e2-aaf7-42c1-8df6-326308751832.png)
then tries to invert from Y to X axis, from "top" to "left", etc...

**Comment by anseki** [comment]
Yes, that is better. :smile:

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
