### ISSUE TITLE
How to center the leaderline but behind the draggable div? 

### ISSUE THREAD

**Issue by vukic-makro** [anseki/plain-draggable#130]
Hey @anseki First of all I'd like to say that this is one of the most amazing things I've ever used. You've really nailed on this feature and it's working extremely well for me. 

However due to the designs which were requested I need to have the line sort of behind the draggable divs raher than on the same level or above. Also it needs to be starting and ending in hte center of draggable div which I've solved. 

Any additional input into how lines would have lower Z-index than the draggable divs would be greatly appreciated. 

I've tried manually setting z-indexes through inspector but that seems to break everything rather than just show it behind 

Thanks again!

**Comment by vukic-makro** [comment]
![Screenshot 2023-03-12 at 12 56 51](https://user-images.githubusercontent.com/90454404/224543017-af7357db-b504-4487-a593-bb814f2342ab.png)

Here's a screenshot to perhaps give you a better understanding of what I'm trying to solve. Basically when the white line overlaps yellow circle I just want it to be below it rather than above

**Comment by anseki** [comment]
Hi @vukic-makro, thank you for the comment.
Was the issue already solved?
