### ISSUE TITLE
Draggable Collision Control

### ISSUE THREAD

**Issue by vukic-makro** [anseki/plain-draggable#131]
Is there any way that when we have multiple dragable elements on the page none of them can go over each other but they would rather "collide". Like they would just touch border of one another and that's it, no snapping no nothing, just stop there if that happened?

**Comment by anseki** [comment]
Hi @vukic-makro, thank you for the comment.
You can use [`left` / `top` properties](https://anseki.github.io/plain-draggable/#accessor-properties).

**Comment by vukic-makro** [comment]
Awesome, thanks!

**Comment by anseki** [comment]
:smile:
