### ISSUE TITLE
Float plain draggable on load or when scrolled into view

### ISSUE THREAD

**Issue by vukic-makro** [anseki/plain-draggable#132]
Hey there, a question I got from clients is if we can make these divs sort of float on load. What'd be the best approach to do this? 

It should look simmilar to this but the issue I'm getting to is that it is hard to make the lines follow the divs https://www.loom.com/share/669f27aaec694229a3d185b1ba0156e4

I was wondering if you have an option to do something on load before draggables are dragged for the first time and stop it after that?

**Comment by anseki** [comment]
Hi @vukic-makro, thank you for the comment.
Sorry, my English is poor.
Do you mean that you want to do something when the moving the draggable element started?

**Comment by vukic-makro** [comment]
Hey @anseki Basically what i need to happen is that before user has interacted with my component the draggable divs float like 10 pixels up and down. 

Leader lines which I have in between should also sync with that movement. 

All of this needs to happen on load of the page and they should stop floating as soon as there is any interaction with draggable divs from user such as dragging/clicking

**Comment by anseki** [comment]
You can use [`position` method](https://anseki.github.io/leader-line/#position) (A method of LeaderLine, Not PlainDraggable) to update drawn lines for new layout by elements that were moved by your script.

**Comment by vukic-makro** [comment]
Is there any way to add transition to position method? 

When I control position in the way you described it seems to just jump to new position without any transition.

**Comment by vukic-makro** [comment]
Also when using Anim event i keep getting an error in the console 
![Screenshot 2023-03-29 at 11 06 52](https://user-images.githubusercontent.com/90454404/228484669-54ce1573-ce4d-43b1-ad32-19accd61da0c.png)

**Comment by vukic-makro** [comment]
Can you confirm that this is the script that I need to use? https://cdn.jsdelivr.net/gh/anseki/anim-event/src/anim-event.js

**Comment by anseki** [comment]
For example: https://jsfiddle.net/jwdyr9uo/
Note that this is [`TransitionEvent`](https://developer.mozilla.org/en-US/docs/Web/API/TransitionEvent) of DOM and CSS. It is not PlainDraggable, and it is not LeaderLine also.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
