### ISSUE TITLE
Element can't move correctly unless I open the developer console

### ISSUE THREAD

**Issue by ddky16** [anseki/plain-draggable#138]
I have a project with Unity Game Engine about making a Finite State Machine editor, and I'm using plain-draggable to move my state. But every time I open my editor and add a state I can't move it correctly it was stuck on the top left corner.
![image](https://github.com/anseki/plain-draggable/assets/100909635/9699c053-dc0e-4885-a138-60bae8bc01ac)
![image](https://github.com/anseki/plain-draggable/assets/100909635/cc007b67-c8ac-43b0-941e-d5770dd1f984)

**Comment by anseki** [comment]
Hi @ddky16, thank you for the comment.
To reproduce that, could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by ddky16** [comment]
https://jsfiddle.net/#&togetherjs=rmVn684cIH This is the source code. But it was combined with unity for setting the fullscreen canvas

**Comment by anseki** [comment]
I couldn't open your JSFiddle page because of TogetherJS maybe.
It doesn't have to collaborate, and make a normal JSFiddle page without TogetherJS, to make it be open page.

**Comment by ddky16** [comment]
[here is the editor page](https://jsfiddle.net/ddky16/3ymtzrvn/)
it wouldn't include my unity js code

**Comment by anseki** [comment]
Your JSFiddle page didn't work.
It seems that you are using JSFiddle in the wrong way.
JSFiddle is a code playground service to test code snippets, etc. It is not a hosting service to present your code to the public.
That is, the code snippet on JSFiddle page should work even if it has problem.
For example:
https://jsfiddle.net/8qy16d9r/
Drag the blue box.

If you want someone to help finding a bug in your code, you should show the problem on JSFiddle by putting your code that has problem.

**Comment by anseki** [comment]
It's OK. :smile: 
I or someone might be able to help you if you show the problem.

**Comment by ddky16** [comment]
https://github.com/ddky16/fsm-state-unity 
I'm sorry i can't use the jsfiddle but u can try this project

**Comment by anseki** [comment]
It's OK. :smile: 
I or someone might be able to help you if you show the problem.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
