### ISSUE TITLE
I struggle with an « Uncaught ReferenceError: PlainDraggable is not defined« 

### ISSUE THREAD

**Issue by Erwan-BR** [anseki/plain-draggable#139]
Hello,

I tried your incredible library with a really simple exemple, but I don’t know why I have such an error. Here is the simple HTML code i used :

```html

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Test - draggable element</title>
</head>
 
<body>
    <script src="plain-draggable.min.js"></script>
    <p style="background-color: #d4d4d4;">Lorem ipsum dolor sit amet, consectetur
    <span id="draggable" style="background-color: lightskyblue;">adipiscing</span>
    elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
</body>
<script>
  draggable = new PlainDraggable(document.getElementById('draggable'));
</script>
</html>
```

Your help would be really appreciated !

**Comment by anseki** [comment]
Hi @Erwan-BR, thank you for the comment.
The loading the `plain-draggable.min.js` might have failed.
Does the file exist in the same directory with the HTML file?

**Comment by anseki** [comment]
You have to specify [`containment`](https://anseki.github.io/plain-draggable/#options-containment) option if you want to change area for moving the element.

**Comment by anseki** [comment]
You can specify [`leftTop`](https://anseki.github.io/plain-draggable/#lefttop-option) option to make PlainDraggable use `left` and `top` CSS properties instead.
However, using the `scale` may be not good way to re-size the element. That changes scale of coordinates of pointer that is moving also. You might have to adjust the scaled coordinates when event is fired.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
