### ISSUE TITLE
Drop to bottom of container

### ISSUE THREAD

**Issue by BonnieSoftware** [anseki/plain-draggable#141]
This isn't a bug, more so a support request and the reason this is being posted is I came here after reading about the gravity and thinking it is what I'm about to ask about.

What I'd like to do is drag an element, and when I finish dragging it, the element drops to the bottom, that being either the container if there are no other elements, or on top of the highest element below it, so that I can achieve something like this:

![image](https://github.com/anseki/plain-draggable/assets/7858744/d1a91158-4bf0-4a20-888e-255cf7e3486d)

I appreciate the top down nature of web pages, and that this is turning the idea on it's head, so it may be considered a little unconventional, but this is a feature of a grid system many have sought for many years now and your library seems as if it could achieve this.

So I was wondering with a little of your help and knowledge, can we see if we can figure this one out? TIA.

**Comment by anseki** [comment]
Hi @BonnieSoftware, thank you for the comment.
Sorry, my English is poor.
Could you explain that by using other words? Or, Could you show me an example?
I can't understand what the building blocks picture mean.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
