### ISSUE TITLE
cant succesfully import it into own project

### ISSUE THREAD

**Issue by ainzy02** [anseki/plain-draggable#145]
Im trying to use this for a project im making and i am unable to even get started.

**Comment by anseki** [comment]
Hi @ainzy02, thank you for the comment.
The document may help you: https://github.com/anseki/plain-draggable#development
Try the commands for packages.

**Comment by ainzy02** [comment]
I figured out how to import some of the files. Do I need every single file or just package and plain-dragable. Also how do you run the commands, I'm new to this type of stuff.

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that you want to know how to use the library in your HTML page?
You can use the library without importing that by loading the library (only single file) into your HTML page via writing a `<script>` tag.
https://anseki.github.io/plain-draggable/#usage

**Comment by ainzy02** [comment]
thank you

**Comment by anseki** [comment]
😄
