### ISSUE TITLE
help with method

### ISSUE THREAD

**Issue by ainzy02** [anseki/plain-draggable#146]
is there any way to get the position in pixels of the item after it has been dragged

**Comment by anseki** [comment]
Hi @ainzy02, thank you for the comment.
You can use [`left` / `top` properties](https://anseki.github.io/plain-draggable/#accessor-properties) to get the coordinates.
Also, you can use [`onDragEnd` event listener](https://anseki.github.io/plain-draggable/#options-ondragend) to get the coordinates when the element was moved.
