### ISSUE TITLE
Plain-draggable placed below leader-line

### ISSUE THREAD

**Issue by ninjaclown123** [anseki/plain-draggable#147]
I am using plain-draggable with leader-line for an application I am developing. The plain draggable instances always appear below the leader-line instances. Is it possible to make it so that plain-draggable instances are placed above the leader-lines?

![image](https://github.com/anseki/plain-draggable/assets/135505235/187c1a72-8ebe-4828-a3cc-e112f67b4675)

**Comment by ninjaclown123** [comment]
Thanks for the response. It was actually a mistake on my side. For some reason, when the div where I was placing all the plain-draggable instances were inside another div, it would place all the draggables below the leader-line z-indices. Fixed it by not nesting the div where I'm storing the plain-draggable instances.

**Comment by anseki** [comment]
😄
