### ISSUE TITLE
Inline style rewritten by window onscroll event

### ISSUE THREAD

**Issue by typebrook** [anseki/plain-draggable#148]
Related issue #125 

Reproduce with [Example]:
1. resize paragraph element with red border line
2. scroll element to the end, and scroll up
3. element's inline style "width" and "height" are erased

@anseki Is there any way to keep inline style after recalculate for scroll event?

[Example]: https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cscript%20src%3D%5C%22https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fplain-draggable%402.5.14%2Fplain-draggable.min.js%5C%22%3E%3C%2Fscript%3E%5Cn%5Cn%3Cscript%20defer%3E%5Cn%20%20setTimeout%28%28%29%20%3D%3E%20%7B%5Cn%20%20%20%20const%20p%20%3D%20document.querySelector%28%27.result-html%20p%27%29%3B%5Cn%20%20%20%20const%20handle%20%3D%20p.querySelector%28%27strong%27%29%3B%5Cn%20%20%20%20new%20PlainDraggable%28p%2C%20%7B%5Cn%20%20%20%20%20%20containment%3A%20document.body%2C%20%5Cn%20%20%20%20%20%20handle%3A%20handle%2C%5Cn%20%20%20%20%7D%29%3B%5Cn%20%20%7D%2C%201000%29%5Cn%3C%2Fscript%3E%5Cn%3Cstyle%3E%5Cn%20%20.result-html%20p%20%7B%5Cn%20%20%20%20resize%3A%20both%3B%5Cn%20%20%20%20border%3A%202px%20solid%20red%3B%5Cn%20%20%20%20overflow-y%3A%20scroll%3B%5Cn%20%20%20%20height%3A%20300px%3B%5Cn%20%20%7D%5Cn%3C%2Fstyle%3E%5Cn%5Cn%5Cn%2A%2AHANDLE%2A%2A%20They%20were%20lost%20without%20the%20drizzly%20rotate%20that%20composed%20their%20pentagon.%20It%27s%5Cnan%20undeniable%20fact%2C%20really%3B%20authors%20often%20misinterpret%20the%20algeria%20as%20a%5Cncirrate%20begonia%2C%20when%20in%20actuality%20it%20feels%20more%20like%20a%20shoreless%20korean.%20Far%5Cnfrom%20the%20truth%2C%20their%20sheet%20was%2C%20in%20this%20moment%2C%20a%20zincous%20bra.%20What%20we%20don%27t%5Cnknow%20for%20sure%20is%20whether%20or%20not%20the%20literature%20would%20have%20us%20believe%20that%20a%5Cnknuckly%20yacht%20is%20not%20but%20a%20rub.%20This%20is%20not%20to%20discredit%20the%20idea%20that%20the%5Cnsearch%20of%20a%20milk%20becomes%20a%20shortish%20europe.%20An%20able%20error%20without%20hoods%20is%5Cntruly%20a%20foxglove%20of%20crushing%20cycles.%20A%20corky%20waitress%27s%20bacon%20comes%20with%20it%5Cnthe%20thought%20that%20the%20canny%20pizza%20is%20a%20lute.%20A%20lamp%20can%20hardly%20be%20considered%20a%5Cnconjoint%20marimba%20without%20also%20being%20a%20cloth.%20Uptight%20cymbals%20show%20us%20how%20sinks%5Cncan%20be%20ketchups.%20This%20could%20be%2C%20or%20perhaps%20the%20quits%20could%20be%20said%20to%20resemble%5Cnmopey%20hens.%20The%20daisy%20is%20a%20cord.%20A%20botany%20can%20hardly%20be%20considered%20a%20hoodless%5Cntop%20without%20also%20being%20an%20education.%20We%20can%20assume%20that%20any%20instance%20of%20a%5Cntrapezoid%20can%20be%20construed%20as%20a%20logy%20teacher.%20The%20curve%20is%20a%20connection.%20The%5Cnbengal%20of%20a%20current%20becomes%20a%20worthy%20digger.%20Their%20sousaphone%20was%2C%20in%20this%5Cnmoment%2C%20a%20haloid%20Santa.%20In%20ancient%20times%20the%20icicles%20could%20be%20said%20to%20resemble%5Cnmangy%20berets.%20The%20dreams%20could%20be%20said%20to%20resemble%20aery%20cattles.%20Authors%20often%5Cnmisinterpret%20the%20close%20as%20a%20fibroid%20theater%2C%20when%20in%20actuality%20it%20feels%20more%5Cnlike%20a%20windburned%20ghost.%20A%20cedarn%20ellipse%20is%20a%20yogurt%20of%20the%20mind.%20The%5Cnquinsied%20dinner%20reveals%20itself%20as%20a%20whacky%20latency%20to%20those%20who%20look.%20A%5Cntrackless%20diaphragm%27s%20yarn%20comes%20with%20it%20the%20thought%20that%20the%20observed%5Cnbillboard%20is%20a%20may.%20Those%20pedestrians%20are%20nothing%20more%20than%20factories.%20An%20oval%5Cnis%20a%20ramie%20from%20the%20right%20perspective.%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

**Comment by anseki** [comment]
Hi @typebrook, thank you for the comment.

That case and #125 are completely unrelated.
PlainDraggable has to reset style properties of the target element to recalculate the position and layout. That is, the style properties of the target element should not be changed intendedly after initialization.
The simple and easy solution is wrapping your contents by another element.
[For example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cscript%20src%3D%5C%22https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fplain-draggable%402.5.14%2Fplain-draggable.min.js%5C%22%3E%3C%2Fscript%3E%5Cn%5Cn%3Cscript%3E%5Cn%20%20setTimeout%28%28%29%20%3D%3E%20%7B%5Cn%20%20%20%20const%20elmTarget%20%3D%20document.querySelector%28%27.result-html%20div%27%29%2C%5Cn%20%20%20%20%20%20draggable%20%3D%20new%20PlainDraggable%28elmTarget%2C%20%7B%20handle%3A%20elmTarget.querySelector%28%27p%20strong%27%29%20%7D%29%3B%5Cn%20%20%20%20new%20ResizeObserver%28%28%29%20%3D%3E%20%7B%20draggable.position%28%29%3B%20%7D%29.observe%28elmTarget%29%3B%5Cn%20%20%7D%2C%201000%29%3B%5Cn%3C%2Fscript%3E%5Cn%3Cstyle%3E%5Cn%20%20.result-html%20p%20%7B%5Cn%20%20%20%20resize%3A%20both%3B%5Cn%20%20%20%20border%3A%202px%20solid%20red%3B%5Cn%20%20%20%20overflow-y%3A%20scroll%3B%5Cn%20%20%20%20height%3A%20300px%3B%5Cn%20%20%7D%5Cn%20%20.result-html%20div%20%7B%5Cn%20%20%20%20display%3A%20inline-block%3B%5Cn%20%20%7D%5Cn%3C%2Fstyle%3E%5Cn%5Cn%3Cdiv%3E%3Cp%3E%3Cstrong%3EHANDLE%3C%2Fstrong%3E%20They%20were%20lost%20without%20the%20drizzly%20rotate%20that%20composed%20their%20pentagon.%20It%27s%5Cnan%20undeniable%20fact%2C%20really%3B%20authors%20often%20misinterpret%20the%20algeria%20as%20a%5Cncirrate%20begonia%2C%20when%20in%20actuality%20it%20feels%20more%20like%20a%20shoreless%20korean.%20Far%5Cnfrom%20the%20truth%2C%20their%20sheet%20was%2C%20in%20this%20moment%2C%20a%20zincous%20bra.%20What%20we%20don%27t%5Cnknow%20for%20sure%20is%20whether%20or%20not%20the%20literature%20would%20have%20us%20believe%20that%20a%5Cnknuckly%20yacht%20is%20not%20but%20a%20rub.%20This%20is%20not%20to%20discredit%20the%20idea%20that%20the%5Cnsearch%20of%20a%20milk%20becomes%20a%20shortish%20europe.%20An%20able%20error%20without%20hoods%20is%5Cntruly%20a%20foxglove%20of%20crushing%20cycles.%20A%20corky%20waitress%27s%20bacon%20comes%20with%20it%5Cnthe%20thought%20that%20the%20canny%20pizza%20is%20a%20lute.%20A%20lamp%20can%20hardly%20be%20considered%20a%5Cnconjoint%20marimba%20without%20also%20being%20a%20cloth.%20Uptight%20cymbals%20show%20us%20how%20sinks%5Cncan%20be%20ketchups.%20This%20could%20be%2C%20or%20perhaps%20the%20quits%20could%20be%20said%20to%20resemble%5Cnmopey%20hens.%20The%20daisy%20is%20a%20cord.%20A%20botany%20can%20hardly%20be%20considered%20a%20hoodless%5Cntop%20without%20also%20being%20an%20education.%20We%20can%20assume%20that%20any%20instance%20of%20a%5Cntrapezoid%20can%20be%20construed%20as%20a%20logy%20teacher.%20The%20curve%20is%20a%20connection.%20The%5Cnbengal%20of%20a%20current%20becomes%20a%20worthy%20digger.%20Their%20sousaphone%20was%2C%20in%20this%5Cnmoment%2C%20a%20haloid%20Santa.%20In%20ancient%20times%20the%20icicles%20could%20be%20said%20to%20resemble%5Cnmangy%20berets.%20The%20dreams%20could%20be%20said%20to%20resemble%20aery%20cattles.%20Authors%20often%5Cnmisinterpret%20the%20close%20as%20a%20fibroid%20theater%2C%20when%20in%20actuality%20it%20feels%20more%5Cnlike%20a%20windburned%20ghost.%20A%20cedarn%20ellipse%20is%20a%20yogurt%20of%20the%20mind.%20The%5Cnquinsied%20dinner%20reveals%20itself%20as%20a%20whacky%20latency%20to%20those%20who%20look.%20A%5Cntrackless%20diaphragm%27s%20yarn%20comes%20with%20it%20the%20thought%20that%20the%20observed%5Cnbillboard%20is%20a%20may.%20Those%20pedestrians%20are%20nothing%20more%20than%20factories.%20An%20oval%5Cnis%20a%20ramie%20from%20the%20right%20perspective.%3C%2Fp%3E%3C%2Fdiv%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

BTW, this example uses ResizeObserver for capture resizing the target element.

**Comment by typebrook** [comment]
> the style properties of the target element should not be changed intendedly after initialization.

I see. Really grateful about your quick reply and detailed solution, you are awesome!

**Comment by typebrook** [comment]
> That case and #125 are completely unrelated.

My bad... it should be #124

**Comment by anseki** [comment]
😄
