### ISSUE TITLE
rtl compatability

### ISSUE THREAD

**Issue by robert777robert777** [anseki/plain-draggable#149]
there are some bugs with right to left documents `<body dir="rtl">`

- horizontal autoscroll doesn't work at all. I didn't find a workaround yet.
- with` will-change: transform` elements with negative left position don't work when horizontal scrolling is needed (the element jumps to another position when plain-draggable started) ,but there is an easy workaround for this with css `body {
    width: min-content;
}`
here is a code to demonstrate both bugs:
```
<script src="plain-draggable.min.js"></script>
<body dir="rtl" >
<span style="position:absolute;top:50px;left:-500px;width:100px;height:50px;">drag me</span>
<div style="width:5000px;height:2000px;"></div>
</body>
<script>
(new PlainDraggable(document.querySelector('span'))).autoScroll = true;
</script>
```

**Comment by anseki** [comment]
Hi @robert777robert777, thank you for the comment.

That is correct behavior.
The draggable element is  restricted in an element that is specified for [`containment`](https://anseki.github.io/plain-draggable/#options-containment) option whether the document is `rtl` or not. The `containment` is parent element as default. That is, it is `<body>` element.
So, `<body>` element's `width` never be expanded than viewport by a wider child element. Maybe you know this and you added the `width: min-content`.

If you want a horizontal scrollable document, this may help you:
https://jsfiddle.net/f872vopa/
Note that the current version doesn't support negative scroll value. See `direction` property.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by robert777robert777** [comment]
thanks for the jsfiddle example, it was helpful and eventually i've found a much easier workaround:
instead of using 
`<body dir="rtl>`
i use
 ```
<body dir="ltr">
<div dir="rtl">
  all of my content goes here
</div>
</body>
``` 
and everything (including autoscroll) works as expected

**Comment by anseki** [comment]
Your idea is no good way because the direction should be decided by the document or the user agent.
You can use `direction` property instead of `dir` attribute to override that for `<body>` element, this is more simple and correct HTML that is better way than your code. 
For example:
https://jsfiddle.net/Ld7xejk6/
