### ISSUE TITLE
mouse event in onDragStart method

### ISSUE THREAD

**Issue by krasnoludkolo** [anseki/plain-draggable#150]
Can we access event in onDragStart and similar methods? I would like to know if certain key is pressed (like shift) and that would be very useful.

**Comment by anseki** [comment]
Hi @krasnoludkolo, thank you for the comment.
Current version doesn't support accessing an event object in event listeners.
Then, you have to listen events such as `mousedown`, `touchstart`, etc., by your code.

**Comment by krasnoludkolo** [comment]
Thanks for response, is it possible to add it in next version?

**Comment by anseki** [comment]
Of course I will think that when many requests come.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
