### ISSUE TITLE
Beautiful Script!

### ISSUE THREAD

**Issue by inglesuniversal** [anseki/plain-draggable#17]
Can it retain the position of the dragged item(s) after page refresh or device reboot (mobile)?

Regards

**Comment by anseki** [comment]
Hi @inglesuniversal, thank you for the comment.
Of course you can retain the position via [`left` / `top`](https://anseki.github.io/plain-draggable/#options-left_top) options.

**Comment by anseki** [comment]
No reply came, then I close this issue. :cry:
