### ISSUE TITLE
docs: Provide code for sortable list example

### ISSUE THREAD

**Issue by hawkeye64** [anseki/plain-draggable#19]
On the documentation page, there is an example for sortable list : `This is an example for sortable list. Drag these items to sort these.`. 
The area I am most interested in is how the other items make room when dragged item is moved?
Can you please add to documentation how this is acheived?

**Comment by anseki** [comment]
Hi @hawkeye64, thank you for your comment.
That example uses the [`onDrag`](https://anseki.github.io/plain-draggable/#options-ondrag) event listener to move items.
The source code is very small and simple. Therefore, you can understand that by reading the code, maybe.
Tell me if your code doesn't work.

**Comment by hawkeye64** [comment]
Are you saying that the other items in a list will automatically make room for the item being dragged? If so, than that is not happening for me.

**Comment by anseki** [comment]
Do you mean that you could not understand the source code of that example?

**Comment by hawkeye64** [comment]
I never saw the source code.

**Comment by hawkeye64** [comment]
This is what I am looking at: https://anseki.github.io/plain-draggable/

**Comment by anseki** [comment]
Um...
Do you mean that the other items did not make room automatically when you drag an item, in the example?
Those should move automatically.

**Comment by anseki** [comment]
If the items did not move automatically, please tell me your web browser (name and version).
Also, try again with recent typical web browser such as Google Chrome.

**Comment by hawkeye64** [comment]
I will put a codepen together in next couple of days. I was using chrome. I think the issue is I am using Vue, and I did the list items in a `v-for="n to 10"`. I think Vue and plain-draggable are fight for DOM control.

**Comment by anseki** [comment]
PlainDraggable can be used with Vue.js. Of course I used those together, in some projects.

So, I have to ask once again. The other items in [the example](https://anseki.github.io/plain-draggable/) did not make room automatically when you drag an item with Google Chrome?

BTW, write `v-for="n in 10"`.

**Comment by anseki** [comment]
I don't know why you never saw the source code, but I copied that and implemented Vue.js.
https://jsfiddle.net/3cmbo8h1/
Try to drag an item (in the bottom-right box), with Google Chrome.

**Comment by anseki** [comment]
Could you explain this situation to me?

**Comment by anseki** [comment]
Since you made this issue, I indicated suggestion and example to help you, and I asked you several questions to help you. I spent my time for you.
However you ignored all of those.
Was your issue already solved?

**Comment by hawkeye64** [comment]
Sorry, I am very helpful for your time and suggestions. I just have a lot on my plate right now and didn't want to bog you down so I closed it. I'll be back into it as soon as I can, but this month is going to be bad for time. But, not fair for you to keep it open that long.

**Comment by anseki** [comment]
I see. :smile:
Remember, you can save your time and the person's time if you answer a question from person who tries to help you. And you can do that easily.

**Comment by GDM95** [comment]
It seems like the original poster was simply asking for the full HTML+CSS+JS for the example on this page: https://anseki.github.io/plain-draggable/

It would save me a lot of time if you simply posted that instead of a list of demos with no code associated with them. It isn't in your repo, or I can't find it.

**Comment by anseki** [comment]
Hi @GDM95, thank you for the comment.
Please check the source code of the example. You should find the full HTML+CSS+JS.
