### ISSUE TITLE
connect many dragging elements with lines

### ISSUE THREAD

**Issue by emzachar** [anseki/plain-draggable#21]
Hi,
I'm testing possibility of connecting many dragging elements into a flow.
I'm able to connect elements into pairs, but stucked with connection between pairs. I'm trying to connect element 0 and 4 with a line. 
Could you please support me?

![connect lines](https://user-images.githubusercontent.com/49212844/55437919-7eae6f00-55a0-11e9-8ae5-4cc7ee105ab4.JPG)

Code:

[Plain-draggable06.txt](https://github.com/anseki/plain-draggable/files/3036007/Plain-draggable06.txt)

**Comment by anseki** [comment]
Hi @emzachar, thank you for your comment.
It seems that this issue is a question about LeaderLine.
See document of LeaderLine: https://anseki.github.io/leader-line/
And then, if you still have the question, make an issue in LeaderLine repository, not here.
This is PlainDraggable repository.
