### ISSUE TITLE
Restrict SVG movement?

### ISSUE THREAD

**Issue by LetsHaveASquint** [anseki/plain-draggable#22]
Hi,
I'm using your SVG example as a basis for interacting with an SVG path.
I am trying to restrict movement to the x axis but am failing.
Might you have a suggestion?

![x-only](https://user-images.githubusercontent.com/44786203/55959191-e95e4b00-5c2f-11e9-8756-095e3864d87c.png)

The Fiddle is here: https://jsfiddle.net/Squinter/frc1pL08/11/

Also, my next desire is to control (drag) the corners of a 4-sided SVG shape. I guess a beginning would be the same Fiddle above, but if you have any suggestions I would appreciate them too.

![4-corner-drag](https://user-images.githubusercontent.com/44786203/55959704-e31c9e80-5c30-11e9-98a2-18246ef9cfd0.png)

Thanks.

**Comment by LetsHaveASquint** [comment]
By the way, since these are not really **issues**, is there a better place to ask questions like this?

**Comment by anseki** [comment]
Hi @LetsHaveASquint, thank you for your comment.
GitHub's issue tracking system is sometimes used to support users. That's no problem.
However, you should not mix multiple topics in one issue.
Then I will comment for your first question. Make new issue for second one if you want.

So, I read your example but I couldn't find code for the restricting. Where is that?

Anyway, you can do that by [`containment`](https://anseki.github.io/plain-draggable/#options-containment) option.
See document: https://anseki.github.io/plain-draggable/
For example: https://jsfiddle.net/awm146x9/

BTW, you had better use a dark color in your figures.

**Comment by LetsHaveASquint** [comment]
Will do. Sorry about the green.

I'm not succeeding with top: 0  in my Fiddle, likely because I'm still learning JavaScript.
In the Fiddle I'm using I see the object key containment with a value of field.

What is field? I tried to replace that with {height: 0}, but that failed.

**Comment by LetsHaveASquint** [comment]
Will do. Sorry about the green.

I'm not succeeding with top: 0  in my Fiddle, likely because I'm still learning JavaScript.
In the Fiddle I'm using I see the object key containment with a value of field.

What is field? I tried to replace that with {height: 0}, but that failed.

**Comment by LetsHaveASquint** [comment]
Will do. Sorry about the green.

I'm not succeeding with top: 0  in my Fiddle, likely because I'm still learning JavaScript.
In the Fiddle I'm using I see the object key containment with a value of field.

What is field? I tried to replace that with {height: 0}, but that failed.

**Comment by LetsHaveASquint** [comment]
Will do. Sorry about the green.

I'm not succeeding with top: 0  in my Fiddle, likely because I'm still learning JavaScript.
In the Fiddle I'm using I see the object property containment with a value of field.

What is field? I tried to replace that with {height: 0}, but that failed.

**Comment by anseki** [comment]
Do you mean that the example that I indicated doesn't restrict the moving?

**Comment by LetsHaveASquint** [comment]
No. Your example is perfect. Thanks.
I cannot understand how to use containment: {height: 0} in mine.
My original came from your SVG example. In it both you and I use containment: field. Changing the key pairs to height: 0 breaks the current functionality. So I am lost.

**Comment by anseki** [comment]
Umm...
I can't understand why the `height: 0` breaks the current functionality.
If you show me your code, I might help you.

**Comment by LetsHaveASquint** [comment]
The Fiddle is here: https://jsfiddle.net/Squinter/frc1pL08/11/
Line 30 is where I tried to add the key pair (height: 0). In the current Fiddle I have left it out because it did not work.

**Comment by anseki** [comment]
Your JSFiddle didn't work because loading the library failed.
Also, I confirmed the `containment` option in line 30 is working correctly. However you specified an element that has `height: 240`, not `height: 0`.
You can specify `Rect` object instead of the element.
See document: https://anseki.github.io/plain-draggable/#options-containment

**Comment by anseki** [comment]
I don't know what you want, but I tried to write code with your first figure.
https://jsfiddle.net/5rwon9py/

**Comment by LetsHaveASquint** [comment]
The problem is my ignorance of JavaScript. I'm learning, but I try to do things that are too hard for me! ;)

Anyway, you solved my issue! Thanks.

**Comment by anseki** [comment]
I welcome questions from beginners, and I am also learning now. :smile:
BTW, which did solve the issue? Rect? The last example? Or another?

**Comment by LetsHaveASquint** [comment]
The last example. Perfect.
Thanks!

**Comment by anseki** [comment]
:smile:
