### ISSUE TITLE
publish an npm package

### ISSUE THREAD

**Issue by MAGICSCIENTIST** [anseki/plain-draggable#24]
hi , the plain-draggable is a very useful project for our work. 
but there is a problem that we expect to install your code with npm. 
so is there any plan to publish your work to npm?

------------------------------------------------------------------------------------------------------
i'm sorry that i haven't searh the right key word before . already found it . please close this issuse if you see it.

**Comment by anseki** [comment]
Hi @MAGICSCIENTIST, thank you for your comment.
So, could you close this issue if it was solved?

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
