### ISSUE TITLE
containment moves when scrolling

### ISSUE THREAD

**Issue by Mr-Skribbls** [anseki/plain-draggable#27]
I created a draggable element that has a parent larger than the viewable area on the screen so it is scrollable. I set the elements containment to something inside the viewable area. When I go to the browser and scroll the containment moves along with the scrolling and as a result the element moves as well. I tried setting the target to the scrolling element but this doesn't fix it. do I have to change the containment left and top properties on each scroll event? I would rather not have to do this.

var draggable = new PlainDraggable(domElem[0], {
            snap: {step: '1%'},
            left: coords.left,
            top: coords.top,
            containment: {
              left: layerCoords.left,
              top: layerCoords.top,
              width: layerBounds[2] - layerBounds[0],
              height: layerBounds[3] - layerBounds[1]
            },
            target: $('#plot-container')[0]
          });

**Comment by Mr-Skribbls** [comment]
If I change the containment to be an html element the problem is fixed. However I think using an object should have the same result.

**Comment by anseki** [comment]
Hi @Mr-Skribbls, thank you for your comment.
Your code seems defective, then that does not work.
Could you show me an example to reproduce that case on such as https://jsfiddle.net/ ?

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.
