### ISSUE TITLE
Containment issue: Items that have containment will move when scrolling container

### ISSUE THREAD

**Issue by NathanaelA** [anseki/plain-draggable#30]
1. If you create a div (overflow: scroll) with a div inside that is larger.  
2. Drop in a draggable item inside the inner div.
3. Set a containment
4. Scroll the div - You will see the item move all by itself; seems like the containment causes some weird interaction with scrollable divs...

Updated Fiddle; prior version didn't save...
https://jsfiddle.net/yoc3r1mv/8/

**Comment by anseki** [comment]
Hi @NathanaelA, thank you for the comment.
I tried your example, and it seems there is no problem. The `containment` worked correctly without being affected by the `#outer` scrolling.
What is result you expect?

**Comment by NathanaelA** [comment]
Ok, In screen shots (this is the starting just scrolled down a little to see both Line 1 & Line 2):
![image](https://user-images.githubusercontent.com/850871/63580764-1fef8f00-c55b-11e9-92dd-5a229904bd68.png)
Ok, notice LINE 1 is above LINE 2.

---
Now we scroll the div to the bottom.
![image](https://user-images.githubusercontent.com/850871/63581022-aa37f300-c55b-11e9-86bd-fde0edc03027.png)
See the scroll bar is at the bottom, and you can see "LINE 1" peeking thru at the top.

---
Now we scroll to the middle.
![image](https://user-images.githubusercontent.com/850871/63581076-ca67b200-c55b-11e9-9462-23fca8bbed27.png)
And you can see Line 1 is now below Line 2.

**I DID NOT DRAG ANYTHING**.   I used the scroll bar on the right side to just scroll the area down then up.

**Comment by anseki** [comment]
Yes, of course that is correct behavior.
Since you specified `containment`, the element can't move to outside of that even if the element is moved by scrolling.
See this. 
https://jsfiddle.net/g5j18sdk/
The position of the element is fixed to the top of dashed red box. Also, bottom of the box.

**Comment by NathanaelA** [comment]
I don't want that behavior. :grinning:   In fact I would argue it is the wrong behavior :grinning: 

So, then if that is the normal behavior; how exactly would you make this containment system work inside a div properly with autoscroll on so that moving the scroll does not move "line 1" at all?   I want "line1" to be constrained to be only allowed between Top: 50 to top: 200 pixels of the scroll box.

**Comment by anseki** [comment]
That is correct behavior even if you don't want that because many GUI rendering works based on client viewport or document. Also, many users want that.

So, do you mean that you want the `containment` is changed with scrolling?

**Comment by NathanaelA** [comment]
> So, do you mean that you want the containment is changed with scrolling?
Yes, I believe this is the only way to make scrolling div's work properly.

Can you take https://jsfiddle.net/osptkwua/1/and make "Line 1" stay always contained between the two black lines?

**Comment by anseki** [comment]
Maybe you misunderstood again.
The containment should work based on the document because you specified "Rect".
See document: https://anseki.github.io/plain-draggable/#options-containment
You can specify an element instead. For example, an element that is moved with scrolling.

**Comment by NathanaelA** [comment]
I believe the `Rect` is a broken design when using scrolling. 

Can you take https://jsfiddle.net/osptkwua/2/ and make "Line 1" stay always contained between the two black lines using just the containment system?

**Comment by anseki** [comment]
Yes of course. That is very easy.
https://jsfiddle.net/2f6svqg9/
You misunderstood.

**Comment by NathanaelA** [comment]
Can you do it without using extra elements; but instead with just passing a containment  `rect`?

Using another element to wrap the area is a interesting solution.  :grinning:  .

**Comment by anseki** [comment]
Yes of course you can specify Rect instead of an element.
See document: https://anseki.github.io/plain-draggable/#options-containment

**Comment by anseki** [comment]
For example: https://jsfiddle.net/ghzwLvpo/2/

**Comment by NathanaelA** [comment]
Thank you.   I tried something similar, and it failed -- so I must have done something wrong.

**Comment by anseki** [comment]
Yes, you maybe have to read document.
I'm happy if I could help you. :smile:
