### ISSUE TITLE
@click doesn't work in draggable element

### ISSUE THREAD

**Issue by Alex-Golovin** [anseki/plain-draggable#33]
Hello there, thanks for your work on this library!

I have an issue, @click event doesn't work on elements/components inside draggable element.
Any ideas how to make it works?

Let me know if needed more details.

**Comment by Alex-Golovin** [comment]
I've read similar issue in repo, looks like I need to try 'handle' option

**Comment by anseki** [comment]
Hi @Alex-Golovin, thank you for the comment.
The `click` event of course works even if the `handle` option is not specified.
You can add a listener via `element.addEventListener('click', ...)` method as usual.
