### ISSUE TITLE
Input inside of draggable

### ISSUE THREAD

**Issue by spgonejoker** [anseki/plain-draggable#35]
Hello @anseki 
i want do edit a text inside a draggable (like this: https://codepen.io/spgonejoker/pen/NWWwddK). 
The div container should be fully draggable, but the elements inside don't need to be draggable for the full container. 

Maybe you have an idea how to do this :) The last time you were a big help :+1: 

Greetings

**Comment by anseki** [comment]
Hi @spgonejoker, thank you for the comment.
Sorry, my English is poor.
What does this mean? : "the elements inside don't need to be draggable"
Do you mean that you want to make the elements inside avoid accepting "mouse-drag" event?

**Comment by spgonejoker** [comment]
Hi @anseki 
Yes right :)

**Comment by anseki** [comment]
You can specify an element that accepts the event for [`handle`](https://anseki.github.io/plain-draggable/#options-handle) option.
The element doesn't contain the elements that should avoid accepting the event.
For example: https://jsfiddle.net/bvyedxp3/

**Comment by spgonejoker** [comment]
Hi @anseki 
Thanks for this idea. I have never thought, that something would work this way :)

**Comment by anseki** [comment]
:smile:
