### ISSUE TITLE
Turn off CSS will-change

### ISSUE THREAD

**Issue by ronvillalon** [anseki/plain-draggable#38]
There doesn't look to be an option to turn off CSS will-change from the start. While will-change helps performance, it seems to limit plain-draggable such that scaling produces pixelated draggables.

**Comment by anseki** [comment]
Could you explain about limiting PlainDraggable?

**Comment by ronvillalon** [comment]
There are many use cases where panning/zooming is needed with draggable elements. If you zoom into elements that have will-change: transform as attributes, the result will be pixelated.

**Comment by anseki** [comment]
As I said in another issue, PlainDraggable seems to be not used for now in many cases that has GUI supporting scaling.
Also, `will-change: transform` works fine with scaled element in standard web browsers. (I couldn't understand the "pixelated".)
So, if you want to remove that for your environment, use this:
```js
element.style.willChange = ''
```
