### ISSUE TITLE
Can't resolve 'anim-event', and 'cssprefix ', and 'pointer-event' ...

### ISSUE THREAD

**Issue by NidusP** [anseki/plain-draggable#39]
Failed to compile.

./node_modules/plain-draggable/plain-draggable.esm.js
Module not found: Error: Can't resolve 'anim-event' in 'D:\workspace\zj-sytem\node_modules\plain-draggable'

Hi, i used the command 'npm i plain-draggable'  to Install dependencies yesterday.  I found other bags missing when i wanted to import 'plain-draggable', so i kept on installing others dependencies. So,, can you update the package  'plain-draggable'.

**Comment by anseki** [comment]
Hi @NidusP, thank you for the comment.
If you want to use libraries in development mode, you can install dependencies automatically by using `npm install` command.
This is specification of NPM.
See document: https://docs.npmjs.com/cli/install.html

**Comment by NidusP** [comment]
Ok，thanks a lot...
I'am sorry for that i have an another question. 

I get the message ' {left: 1016, top: 195, snapped: true} ', by 'onMove' function, when the draggable element is snapped.  But I have set several elements to snap  it， how can i know which one element  snapped the draggable element? 

Thank you so much for your assistance,  have a nice day.

**Comment by anseki** [comment]
Could you create new issue for another question after close this issue?

**Comment by NidusP** [comment]
thanks

**Comment by BloodWorkXGaming** [comment]
I don't really understand when those libraries are needed? 
Only during development, wouldn't it make sense to add it to "devDependencies" then?

Sorry if this is a stupid question, am a js beginner.

**Comment by anseki** [comment]
Hi @BloodWorkXGaming, thank you for the comment.
As you said, PlainDraggable needs no library. And `devDependencies` libraries are required only in development mode.
@NidusP tried to use PlainDraggable in development mode.
See https://github.com/anseki/plain-draggable/issues/39#issuecomment-555821015

**Comment by anseki** [comment]
@kkarpeev,
Sorry, my English is poor.
Do you mean that you can't install those modules automatically?
If so, could you show me the commands you did?
