### ISSUE TITLE
reposition of draggable object when parent is scaled

### ISSUE THREAD

**Issue by goepfert** [anseki/plain-draggable#41]
Hi, first - thank you @anseki for sharing your work!

I'm having some issues when a draggable object is inside a scaled div for example. I created a fiddle (https://jsfiddle.net/goepfert/bms9L3xz/) to show what I mean.

Basicly I can see two somehow related features:

1) Scale parent div by 0.5 (Button 0.5), move/drag the green draggable div and then force draggable.position() by Button click 'Reposition'. Now evertime you force a reposition the draggable object jumps a little to the top left.

2) Reload. Move/Drag the draggable object a litte. Scal by factor of 2 (Button 2) and the scroll. Now evertime you force a reposition the draggable object jumps a litte to the bottom right. Remark: If I overwrite the draggable.position() method the behaviour is the same.

Note: To match the mouse position to the dragging object while dragging, the position is calculated manually via ondrag. This has no influence to the obove mentioned issues.

I'm unable to find out what causes these style transformations nor how to fix them. They seem to be related to the scaling factor.

I'm very grateful for any help!

**Comment by anseki** [comment]
Hi @goepfert, thank you for the comment.
This example may help you.
https://jsfiddle.net/x8bvqr2f/

**Comment by goepfert** [comment]
Hi @anseki ,
in your example I can see similar jumps/repositions of the draggable object as well. E.g. if you drag it somewhere and then manually change the size of the bottom right output window of the fiddle page.

![grafik](https://user-images.githubusercontent.com/946381/70793513-bd393200-1d9b-11ea-801d-c7d723d7f7e2.png)

**Comment by anseki** [comment]
I see.
Try this:
https://jsfiddle.net/ue9khnyz/
But this is not beautiful.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
