### ISSUE TITLE
Typescript Typedef

### ISSUE THREAD

**Issue by BloodWorkXGaming** [anseki/plain-draggable#43]
Hello,

I am trying to use plain-draggable in combination with typescript, however I can't rely on the typesafety as there are no type definitions.

Would it be possible to add a .d.ts file with the types? or create a official @types/plain-draggable package?

**Comment by anseki** [comment]
Hi @BloodWorkXGaming, thank you for the comment.
You can write the type definition for PlainDraggable to `@types` and publish it on [`DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by anseki** [comment]
Hi @tapmeppe, thank you for the comment.
You can write and publish it.
https://github.com/DefinitelyTyped/DefinitelyTyped
