### ISSUE TITLE
Need onSnap event.

### ISSUE THREAD

**Issue by dr-error** [anseki/plain-draggable#45]
Hi,
I am trying to attach a sound effect 'on snap'. Can you point me in a direction on how to do this with the current code? I'm aware of the onDragEnd event. I like to catch a snap while dragging.  Maybe can you add an onSnap event in a future release? Or maybe it can be added as a property to the onMove event?
I love plain-draggable very much so far! 
Thx,
Marco

**Comment by anseki** [comment]
Hi @dr-error, thank you for the comment.
The `snapped` property in `onMove` event that you want is already supported.
See document: https://github.com/anseki/plain-draggable#onmove

**Comment by dr-error** [comment]
Thank you for your fast reply!
I missed the snapped property. 
No further issues.

**Comment by anseki** [comment]
:smile:
