### ISSUE TITLE
steps option on boundingBox

### ISSUE THREAD

**Issue by sebgrosc** [anseki/plain-draggable#46]
Hi Anseki,

nice project! Is it possible to have the steps option just on a specific target? Unfortunately, that is not working.
Example:
`{ boundingBox: document.getElementById('target') },
					{
						boundingBox: {
							x: 35,
							y: 280,
							width: 200,
							height: 80,
							step: 35
						}
					}`
And, if I have multiple draggable elements, is it possible to prevent that they have the same coordinates? Thank you!

**Comment by anseki** [comment]
Hi @sebgrosc, thank you for the comment.
Of course you can specify an element to `boundingBox` of `SnapTarget`.
https://anseki.github.io/plain-draggable/#structure-and-abbreviation

Could you make new issue for another topic?

**Comment by sebgrosc** [comment]
Hi @anseki , thank you for your fast reply. Yes, I was able to create this rectangle but as described by the example above it is not handling the `step: 35` option. I have read your documentation before but haven't seen this example related to the boundingBox.
If I add e.g. `{ x: { step: 35, start: 0 }` then it works but not for the boundingBox.

**Comment by anseki** [comment]
You seem to be misunderstanding the `snap` option.
You specified `boundingBox.step` but that is not existing.
See document again.
https://anseki.github.io/plain-draggable/#structure-and-abbreviation

The `boundingBox` is used for indicating four lines. Therefore `step` that was specified by you is meaningless.

If you want to specify `left` of the element for the `start`, you can do that.
For example:
```js
const boundingBox = document.getElementById('target').getBoundingClientRect(),
  draggable = new PlainDraggable(document.getElementById('draggable'), {
    snap: {
      x: {start: boundingBox.left, end: boundingBox.right, step: 35},
      base: 'document'
    }
  });
```

**Comment by sebgrosc** [comment]
Thanks for your reply. Yes, that was the question whether this is possible to define steps in a boundingbox.
