### ISSUE TITLE
multipile dragging elements - prevent same coodinates

### ISSUE THREAD

**Issue by sebgrosc** [anseki/plain-draggable#47]
Hi @anseki ,

if I have multiple draggable elements, is it possible to prevent that they have the same coordinates.
Thank you!

**Comment by anseki** [comment]
Hi @sebgrosc, thank you for the comment.
This example may help you:
https://anseki.github.io/plain-draggable/#ex-040-stage
It uses [`onDrag`](https://anseki.github.io/plain-draggable/#options-ondrag) option.
