### ISSUE TITLE
 the event of ondragover and ondragleave  not work?

### ISSUE THREAD

**Issue by jingxl** [anseki/plain-draggable#5]
hi ,sir,  the event of ondragover and ondragleave  not work  when I drag one element to another drag element(e.g:  drag a button  to  a div element)
but, what can I do?

**Comment by anseki** [comment]
hi @jingxl, thank you for the report.
So, which element did you pass to PlainDraggable? And which element does have the problem?
Could you show me an example? E.g. using https://jsfiddle.net/

**Comment by anseki** [comment]
No reply came, and I close this issue.
