### ISSUE TITLE
change function

### ISSUE THREAD

**Issue by nSanhuezaKrino** [anseki/plain-draggable#50]
@anseki Is there a function that changes an element's div?

**Comment by anseki** [comment]
Hi @nSanhuezaKrino, thank you for the comment.
What is "element's div"?
Do you mean that you want to use an element other than `<div>` element?
You can specify any element that has a bounding-box.
https://anseki.github.io/plain-draggable/#constructor

**Comment by nSanhuezaKrino** [comment]
for example if I want to change an <input>from one  <div1> to another  <div2>

**Comment by nSanhuezaKrino** [comment]
for example if I want to change an input from one div to another div

**Comment by nSanhuezaKrino** [comment]
@anseki for example if I want to change an input from one div1 to another div2

**Comment by kaysaith1900** [comment]
Hi @nSanhuezaKrino , i will prefer  you control that by yourself, after you clickd the input ,at the same time you move this input into document.body , then you can drag . and after you decide put it into the target div2, after you grip, at the same time you insert the input to target div2.

**Comment by nSanhuezaKrino** [comment]
@anseki I understand, thank you

**Comment by anseki** [comment]
@kaysaith1900, thank you for your help.

@nSanhuezaKrino, So, was the issue solved?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
