### ISSUE TITLE
is there a method that you can give a callback after the draggable element trigger the snap area ?

### ISSUE THREAD

**Issue by kaysaith1900** [anseki/plain-draggable#51]
Hi @anseki , is there a method that you can give a callback after the draggable element trigger the snap area ? 
sometimes  i want to dynamically switch the snap area display style. i really need a convenient method to control that .

**Comment by anseki** [comment]
Hi @kaysaith1900, thank you for the comment.
You can know whether the draggable element was snapped or not by `snapped` property that is passed to event handlers.

**Comment by kaysaith1900** [comment]
Hi @anseki , than you for your reply.

I have more than one snap condition， how should i know which one the draggable element has passed ?

for example: i have two ruler line, horizontal center line, vertical line, when the draggable passed the horizontal lien , i want to display it , the same as vertical line.

but when i console the event handler , only snapped: boolean , i don't which one i need display ?

**Comment by anseki** [comment]
Does this help you?
https://jsfiddle.net/qy4hntek/
https://github.com/anseki/plain-draggable/issues/26

**Comment by kaysaith1900** [comment]
Hi @anseki , 

yes i did it that kind of your example too. 

if i can control in snap object part, i think it will be more convenient : ) 
for example:

snap: {
  { x: 130, (snapped) => {  do something  }
}

any way it depends on you. : )

**Comment by anseki** [comment]
Thank you for your proposal.
However, that is not good idea because the `snap` option is not simple, for example a `Rect` is resolved to four lines, therefore that should make many confusion.
https://anseki.github.io/plain-draggable/#structure-and-abbreviation
And also, that is not very convenient, and finding the target is easy in many cases.

**Comment by kaysaith1900** [comment]
got it , thank you for you reply. : )

**Comment by anseki** [comment]
:smile:
