### ISSUE TITLE
how to set a wall that draggable can't move into

### ISSUE THREAD

**Issue by towify** [anseki/plain-draggable#52]
Hi,

i find that there is an example in the document,  "You can control the moving with coordinates of the draggable element and a mouse pointer that drags."  it is really useful. but i can't find the method.

how can i set an rect hole in the containment, that the draggable element can't move into it ?

**Comment by anseki** [comment]
Hi @towify, thank you for the comment.
You can do that easily by using [`onDrag`](https://anseki.github.io/plain-draggable/#options-ondrag) event listener.
Also, you can see the code of the example.

**Comment by towify** [comment]
@anseki  thanks  for replying

**Comment by anseki** [comment]
:smile:
