### ISSUE TITLE
is there a method that i can set the resistance when the draggable element touch the snap edge ?

### ISSUE THREAD

**Issue by towify** [anseki/plain-draggable#53]
Hi,
Is there a method that i can set a custom resistance when the draggable element touch the snap edge ?

**Comment by anseki** [comment]
Hi @towify, thank you for the comment.
Sorry, what does "resistance" mean?

**Comment by towify** [comment]
@anseki , it is the opposite of gravity  : )

**Comment by anseki** [comment]
You can specify [`gravity`](https://anseki.github.io/plain-draggable/#snap-gravity) option for Snap.

**Comment by anseki** [comment]
?

**Comment by anseki** [comment]
Was this issue solved???

**Comment by anseki** [comment]
Could you explain your situation for another issue?
