### ISSUE TITLE
Call plain-draggable by class names instead of ids.

### ISSUE THREAD

**Issue by alextate4** [anseki/plain-draggable#55]
Is it only possible to select a single element by its id? The project I'm working on is a floor plan with hundreds of elements which would be nice to call by their class name.

**Comment by anseki** [comment]
Hi @alextate4, thank you for the comment.
Selecting the element is not supported.

**Comment by anseki** [comment]
No reply came, my message was ignored, then it was closed.
However, note that the comment referred to "selecting", not "calling".
