### ISSUE TITLE
Containment so SVGs cannot touch

### ISSUE THREAD

**Issue by alextate4** [anseki/plain-draggable#56]
For our floorplan, we want to set all items so they cannot move over each other when they touch. Is this possible?

http://colab.web.csit.jccc.edu/

**Comment by anseki** [comment]
Hi @alextate4, thank you for the comment.
This example may help you:
https://anseki.github.io/plain-draggable/#ex-040-stage

**Comment by alextate4** [comment]
I have read this multiple times. I understand how an element can be restricted to an axis, however, I would like all elements to be restricted by their bounding boxes. Do you know how this can be done?

**Comment by anseki** [comment]
You can do that by using [`onDrag`](https://anseki.github.io/plain-draggable/#options-ondrag) event handler.

**Comment by alextate4** [comment]
I created a JSfiddle. I am sorry I am not very experienced but I know what I want to do. Can you help?

`//I want none of the SVG elements to touch each other when moved. I tried an ondrag and it doesn't work. I don't understand how to set the container to the outer bounding box of each element rather than just 1 axis. 

var global = $('#masterPlan'); //this doesn't work...
var stationary = $('#stationaryObjects'); //this doesn't work...

var moveable = new PlainDraggable(document.getElementById('moveableObjects')); //this doesn't work. all moveable SVGs are in this group

var tealCouch = new PlainDraggable(document.getElementById('southEastCouch-1'));
var blueChair = new PlainDraggable(document.getElementById('blueChair-1'));
var blueStool = new PlainDraggable(document.getElementById('blueStool-1'));
var blackChair = new PlainDraggable(document.getElementById('blackChair-1'));
var greenChair = new PlainDraggable(document.getElementById('greenLowChair-1'));

/* document.addEventListener("ondrag", function(event) {
  greenLowChair.style.fill = "red";
}); */

moveable.containment = {left: 20, top: 20, width: 800, height: 0}; //This doesn't work. Can everything in this moveable group be called??

/* 
blueChair.containment = {left: 20, top: 20, width: 800, height: 0}; 
blueStool.containment = {left: 20, top: 20, width: 800, height: 0}; 
blackChair.containment = {left: 20, top: 20, width: 800, height: 0}; 
greenChair.containment = {left: 20, top: 20, width: 800, height: 0}; */ //these work but very tedious.

tealCouch.containment = {left: 20, top: 20, width: 800, height: 0}; //this works, but it is not going to do what I want. I want the outer box of every SVG to be a container.

$('#blackChair').on('drag', function(e) {
	blackChair.containment = {left: 20, top: 20, width: 800, height: 0};
}); //this doesn't seem to be working. I also do not understand how to set the containment to only the outer bound box..

document.addEventListener("ondrag", function(e) {
  tealCouch.containment = {left: 20, top: 20, width: 800, height: 0}; 
}); //does nothing....`

https://jsfiddle.net/atate4/efoat4L3/85/

Thank you!

**Comment by anseki** [comment]
Could you explain the issue?
Do you mean that the `document.addEventListener("ondrag"...` doesn't work?

**Comment by anseki** [comment]
Could you explain the issue about your code?
Do you mean that the `document.addEventListener("ondrag"...` doesn't work?

**Comment by anseki** [comment]
I don't know what your code means.
Anyway, this example may help you:
https://jsfiddle.net/tfn4sb1o/

**Comment by alextate4** [comment]
This has helped me so much! Thank you!

**Comment by anseki** [comment]
:smile:
