### ISSUE TITLE
Move and group SVG.

### ISSUE THREAD

**Issue by alextate4** [anseki/plain-draggable#57]
We would like to be able to group, move, and rotate objects together through an event like a mouse drag and removing single items in that group with a shift+click. Is this possible?

**Comment by anseki** [comment]
Hi @alextate4, thank you for the comment.
Of course you can do that.
https://anseki.github.io/plain-draggable/#options-left_top

**Comment by alextate4** [comment]
Maybe this will make sense if I am more specific.

<img width="373" alt="Screen Shot 2020-04-24 at 6 58 33 AM" src="https://user-images.githubusercontent.com/24833973/80231229-b5767d80-8618-11ea-93ac-0307eda0539f.png">

When the mouse is clicked and dragged, we would like to create a visual box that represents the area of elements being selected, seen in programs such as Adobe Illustrator, Photoshop, etc. When this visual box touches each element, the will be added to a group that can then be manipulated all together. Do you know how this can be done?

**Comment by anseki** [comment]
Generally speaking, changing status (flag) of each object is used.
When an object is clicked, change the selected object. When an object is clicked with pressing <kbd>Ctrl</kbd> key, add the selected objects.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
