### ISSUE TITLE
Rotate feature

### ISSUE THREAD

**Issue by alextate4** [anseki/plain-draggable#58]
We would like to include a rotate handle feature in this project. Do you have this as a method for this library? Thank you for all of the help!

**Comment by anseki** [comment]
Hi @alextate4, thank you for the comment.
Of course you can do that.
For example, make a rotate handle be draggable, and rotate an element with dragging.

**Comment by anseki** [comment]
No reply came, my message was ignored, then it was closed wordlessly.
However, note that the issue is unrelated to the library.
