### ISSUE TITLE
Arrow position is not updating dynamic dom div  

### ISSUE THREAD

**Issue by Veeramuthur** [anseki/plain-draggable#59]
Hi thank you.. it very useful

i am using DOM to generate the div element and i am using leaderline and plain dragable but position is not updating.

code:

for (var i = 0; i < LinkElement.length; i++) {
var plaincomponent = new LeaderLine(
document.getElementById(LinkElement[i].LeftElementName),
document.getElementById(LinkElement[i].RightElementName),
{ color: '#ff0000', size: 2, path: 'straight', dash: { animation: true } });
function fixLine() {
startant.position();
plaincomponent.position();
}
new PlainDraggable(document.getElementById(LinkElement[i].LeftElementName), { onMove: fixLine, containment: document.body });

new PlainDraggable(document.getElementById(LinkElement[i].RightElementName), { onMove: fixLine, containment: document.body });
}

it only updateing the position my last element (e.g i= 4) its not working for first element(e.g i=1).. please help me to solve this..

thanks..

**Comment by anseki** [comment]
Hi @Veeramuthur, thank you for the comment.
The `plaincomponent` was overwritten repeatedly, and you called `plaincomponent.position()` method. Therefore, only last one was updated.
You can define those individually, and you can call the method of each one.
For example:
https://jsfiddle.net/jn4xLtdf/
This is specification of ECMAScript (JavaScript), it is unrelated to PlainDraggable.
See document:
https://developer.mozilla.org/en-US/docs/Glossary/Hoisting
https://developer.mozilla.org/en-US/docs/Glossary/Scope
And also, `startant` is not defined.

**Comment by Veeramuthur** [comment]
Hi @anseki , thank you for quick update.

The jsfiddle is very helpful, but 

 var LinkElement = [
  { LeftElementName: 'item-0l', RightElementName: 'item-0r' },
  { LeftElementName: 'item-0r', RightElementName: 'item-1l' },
  { LeftElementName: 'item-1l', RightElementName: 'item-1r' },
   { LeftElementName: 'item-1r', RightElementName: 'item-2l' },
    { LeftElementName: 'item-2l', RightElementName: 'item-2r' },
    ];

using this LinkElement  array we will connect div zigzag structure, basically here we are getting one incoming arrow and one outgoing ,if we move 'item-0r' incoming arrow is not updating the position.

please help to find this.find my attachment

thankyou @anseki 
[plaindragable.txt](https://github.com/anseki/plain-draggable/files/4550400/plaindragable.txt)

**Comment by anseki** [comment]
Could you show me your code by using JSFiddle?

**Comment by Veeramuthur** [comment]
Hi @anseki 

Here is my code: https://jsfiddle.net/veeramuthu/vj6e8k4d/2/

**Comment by anseki** [comment]
I see.
Your code has a simple bug about the logic.
The `LinkElement` is an array of lines. That is, one element of the array means one line.
However, that doesn't  be paired each draggable element.
So, you can solve this by adding an array (or hash) for elements.
For example:
https://jsfiddle.net/awmtkg01/

**Comment by Veeramuthur** [comment]
Hi @anseki 

Thank you so much..
The jsfiddle logic solved my problem and once again thank you for quick response.

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
So, could you close this issue if it was solved?
