### ISSUE TITLE
double click

### ISSUE THREAD

**Issue by Idea2Soft** [anseki/plain-draggable#6]
its look like the drag option take the double click event and i can't use it
any solution?

**Comment by anseki** [comment]
Hi @Idea2Soft, thank you for the comment.
So, could you show me example?
E.g. using https://jsfiddle.net/

**Comment by anseki** [comment]
For example:
https://jsfiddle.net/r730t24k/

**Comment by anseki** [comment]
Was this issue solved?
You should comment.

**Comment by Idea2Soft** [comment]
In your example is good  but in my web site its not work i think its my
issue

בתאריך יום ב׳, 4 ביוני 2018, 12:35, מאת anseki ‏<notifications@github.com>:

**Comment by Idea2Soft** [comment]
I think it’s because I use a group element in svg

**Comment by anseki** [comment]
I see.
If you show an example,  I or somebody might be able to help you. :smile:
