### ISSUE TITLE
Element not moving vertically unless resizing the browser

### ISSUE THREAD

**Issue by rockcs1992** [anseki/plain-draggable#65]
Hi, thanks for the awesome work of making this library.

I'm playing around with it and trying something really simple. Here is a fiddle that works as expected:
https://jsfiddle.net/9wz0t81g/

However when I try that on my local machine within a single html file, the element only moves horizontally and cannot move vertically. Yet after I resize the browser, the issue is gone and it works normally. Not sure if you have encountered anything like this before, or if I did anything wrong with the html file.

```
<!doctype html>
<html>
  <head>
    <title>Test</title>  
  </head>
  <body>
        <span id="draggable">Drag This</span>

        <script src="https://cdn.jsdelivr.net/npm/plain-draggable@2.5.10/plain-draggable.min.js"></script>
  <script>
         var draggable = new PlainDraggable(document.getElementById('draggable'));
  </script>
  </body>
  <style>
      html, body { height: 100%; }
#draggable {
  display: inline-block;
  padding: 3px;
  font-weight: bold;
  color: white;
  background-color: indianred;
}
  </style>
</html>
```

**Comment by anseki** [comment]
Hi @rockcs1992, thank you for the comment.

Your HTML code is incorrect without regard to the PlainDraggable.
Try this:
```html
<!doctype html>
<html>
  <head>
    <title>Test</title>  
  <style>
      html, body { height: 100%; }
#draggable {
  display: inline-block;
  padding: 3px;
  font-weight: bold;
  color: white;
  background-color: indianred;
}
  </style>
  </head>
  <body>
        <span id="draggable">Drag This</span>

        <script src="https://cdn.jsdelivr.net/npm/plain-draggable@2.5.10/plain-draggable.min.js"></script>
  <script>
         var draggable = new PlainDraggable(document.getElementById('draggable'));
  </script>
  </body>
</html>
```
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style

**Comment by rockcs1992** [comment]
Oops. I haven't written everything in a single html file for a while and forgot where to place the style tag. Such a stupid mistake lol. Thanks for pointing it out. I will close the issue.

**Comment by anseki** [comment]
:smile:
