### ISSUE TITLE
Draggable div does not follow mouse position after parent div is zoomed

### ISSUE THREAD

**Issue by weiyuanC** [anseki/plain-draggable#67]
My project required the parent div to be scalable, but after zooming in or out, plain-draggable children div will not follow the mouse position when dragging. In my case, all draggable children stay within the scalable parent div. Is there any solution to this?

Zoom by using CSS transform scale, zoom by scrolling.

```
draggable.onDrag = (newPosition) => {
      const boundingRect = drawArea.current.getBoundingClientRect(); // parent div 
      newPosition.left = (boundingRect.left + (newPosition.left - boundingRect.left)) / currentScale; //e.g currentScale = 1 or 1.1 or 2
      newPosition.top = (boundingRect.top + (newPosition.top - boundingRect.top)) / currentScale;
}
```
It works well when scale value = 1
Tried dividing the scale value, but it does not work.

**Comment by anseki** [comment]
Hi @weiyuanC, thank you for the comment.
This may help you: https://github.com/anseki/plain-draggable/issues/13

**Comment by weiyuanC** [comment]
I have seen that post, but I still don't get it.

In this example: [https://jsfiddle.net/5rzkxpaf/](url)

the example will not work when I change the JS SCALE value and the transform value in CSS to the same value.

So, the issue is I shouldn't use transform scale?

**Comment by anseki** [comment]
I see.
Does this help you?
https://github.com/anseki/plain-draggable/issues/54

**Comment by weiyuanC** [comment]
Yes! This example does help.

In this example: [https://jsfiddle.net/ue9khnyz/](url)

What is line 21 and 22 doing? I tried removing them and it is still working.

**Comment by anseki** [comment]
Those lines fix the position of the element when the moving the draggable element started (before `onDrag` function is called).

**Comment by weiyuanC** [comment]
Thank you so much for the quick response and patience! It works perfectly now!

I have one more question, how do I disable the whole draggable?

Tried doing:
`draggable.disabled = true`
but it doesn't work

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue and make new issue for another topic?
