### ISSUE TITLE
Trying to disable draggable

### ISSUE THREAD

**Issue by weiyuanC** [anseki/plain-draggable#69]
I know there is a disabled property in the docs, but I can't figure out how to use it.

Any example around?

**Comment by anseki** [comment]
Hi @weiyuanC, thank you for the comment.
Could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by weiyuanC** [comment]
[https://jsfiddle.net/cwy24/sby9wm1a/2/](url)

In the example above, I want to disable draggable when stopDrag is true.

**Comment by anseki** [comment]
I tried your code.
Then your code doesn't disable the draggable because that has a bug.
The draggable never be disabled because your code doesn't change `disabled` property.
See document: https://anseki.github.io/plain-draggable/

**Comment by weiyuanC** [comment]
Thanks a lot for the help! The reason my code didn't work back then is because of some re-rendering issue.

I will close this issue now, thank you for this wonderful repo!

**Comment by anseki** [comment]
:smile:
