### ISSUE TITLE
resize element?

### ISSUE THREAD

**Issue by songsgroup** [anseki/plain-draggable#7]
can add resize element?

**Comment by anseki** [comment]
Hi @songsgroup, thank you for the comment.
Of course you can resize the element.

**Comment by anseki** [comment]
Do you mean that you want to resize another element (not draggable element) by dragging?

**Comment by songsgroup** [comment]
I want to  resize draggable element ,Is there an example?

**Comment by anseki** [comment]
If you want to resize draggable element without dragging, you can do that by specifying just only the size, very easily.

For example:
```js
draggable.element.style.width = '100px';
draggable.position(); // Update position
```

**Comment by songsgroup** [comment]
thanks  ,i want to resize draggable element with mouse drag move. 
thanks.

**Comment by anseki** [comment]
As I said, It seems that you want to resize another element (not draggable element) by dragging.
For example: https://jsfiddle.net/byaje56n/

**Comment by anseki** [comment]
No reply came, and I close this issue. :cry:
