### ISSUE TITLE
how to make the content editable and draggable

### ISSUE THREAD

**Issue by guizmoau** [anseki/plain-draggable#71]
Thanks for the great work and this lib is functionning perfectly so far, I just have a very specific use case that might be able to do from the standard lib functions (without adding specific code in the lib)

Here is my actual draggable div with inner div with text content made editable

<div id="existence-1" class="is-existence node plain-draggable">
<div id="existence-1-title" class="node-content content is-large" contenteditable="true">existence-1</div>
<button class="button">button1</button>
<button class="button">button2</button>
<button class="delete is-small"></button>
</div>

when I click it get the drag so I cant edit...I want to be able to edit when I click on text and drag still the outer div.

How is it possible to do so ?

Thanks a lot

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
