### ISSUE TITLE
How to make a div box contains div boxes that have draggable elements in them be  elongated automaticlly?

### ISSUE THREAD

**Issue by SHEELINUNI** [anseki/plain-draggable#72]
Hi anseki, thanks for your perfect libs, I implement my project well!  But now I face a problem, I create a div box outside all the div boxes that contains draggable elements, and I use "height:auto;" in the outside box to make the outside div box be elongated automatically if I add more draggable elements into it (give them more space to move), these codes works well without I use plain-draggable. But when I use plain-draggable to them, the outside div box cannot elongate anymore, I wonder wether there a way to fix that ? 
Here's the example without using draggable:
https://jsfiddle.net/Shellin/ar3uzdL2/5/
Here is what happened after I use draggable: (that the result picture on my pc ):
![$QKZ_UENQ2}{ )IM@ SKS}P](https://user-images.githubusercontent.com/44541579/110924982-9c280e00-835d-11eb-99ae-43f55eafdaee.png)

the outside div become a line and the inside div boxes are mixed togther, when I set the height of outside div box, it works well, but I want the size of the page can be changed only the inside draggable div become more...

Here's the code for my using draggable version(sorry for that I dont know how use 3rd praty's js lib in jsfiddle), so I just put my code into it but it cannot run as it shows on my pc(the plain-draggable.js and Leaderline.js cannot be loaded): https://jsfiddle.net/Shellin/gx9hnp8L/

**Comment by anseki** [comment]
Hi @SHEELINUNI, thank you for the comment.
First of all, was that issue solved? https://github.com/anseki/leader-line/issues/206#issuecomment-790742703
And, is this issue related to that?

**Comment by SHEELINUNI** [comment]
Hi @anseki , the last issue has been sloved, thank you for your help, this is a new issue I faced.

**Comment by anseki** [comment]
I see.
So, do you mean that you want render the second example same as the first one?

**Comment by SHEELINUNI** [comment]
Yes

**Comment by anseki** [comment]
This may help you:
https://jsfiddle.net/3bfeny0u/
Your code is not easy to read. You had better write correct code to avoid making bugs.

**Comment by SHEELINUNI** [comment]
Thanks for your help, maybe there are some bugs in my orgianl code, sorry for that because I am new to web page development. Thank you for your patient guidance.
But for this part, it still have overlap of the div boxes for the version you send to me, I mean this part: 
![Uploading FS7(%TPFOPG64W]]UF7%LWL.png…]()
Becasue I want put lots of images in that div box and make it no overlap just like the above images, and when the images become more and more, the div box can be longer and fit them in

**Comment by SHEELINUNI** [comment]
Oh , seems I find what's the problem is, I should not using "top" to change the position if I use "addEventListener()", Thanks for your help. This one has been finshed.

**Comment by anseki** [comment]
Your example code specifies the position of each element. I don't know why that, but those are not the positions you want maybe.
The elements that has `position: relative` are usually positioned automatically. Then, removing the code that specifies the position may solve that.

BTW, you should use syntax checker such as [ESLint](https://eslint.org/) at least, and I recommend [VS Code](https://code.visualstudio.com/) editor that has ESLint extension.

**Comment by anseki** [comment]
No, the `top` is not related to `addEventListener`.

**Comment by SHEELINUNI** [comment]
Yes, you are right, thanks for your suggestion ! 

> Your example code specifies the position of each element. I don't know why that, but those are not the positions you want maybe.
> The elements that has `position: relative` are usually positioned automatically. Then, removing the code that specifies the position may solve that.
> 
> BTW, you should use syntax checker such as [ESLint](https://eslint.org/) at least, and I recommend [VS Code](https://code.visualstudio.com/) editor that has ESLint extension.

**Comment by SHEELINUNI** [comment]
> No, the `top` is not related to `addEventListener`.

When I add position:relative and detele top in my orginal code, it now works as what I want it do...
So maybe from the beginning I should add poisition:relative ? Any it works fine now. 
![HT0MU69EWL46K GST323WMN](https://user-images.githubusercontent.com/44541579/110954971-0d7ab780-8384-11eb-9d97-237f23f18242.png)

**Comment by SHEELINUNI** [comment]
I'm sorry to have delayed your time because of my own mistake... And my english is not too good, thank you again for your help! Good js library !

**Comment by anseki** [comment]
You don't have to add the `position: relative` usually because that is default.
Therefore, you have to only remove specifying the position.

I'm glad if I could help you. :smile:
