### ISSUE TITLE
ZOOM on parent of draggable elements as the first example on documentation page 

### ISSUE THREAD

**Issue by lucaslgr** [anseki/plain-draggable#74]
How I could make zoom in parent of draggable elements, a similar in what did you do in the first example of this page? https://anseki.github.io/plain-draggable/#options

**Comment by anseki** [comment]
Hi @lucaslgr, thank you for the comment.
The first example doesn't support the zooming.
This is screen shot of first example:
![ss01](https://user-images.githubusercontent.com/4763469/111796854-edab3c80-890b-11eb-9033-a9a3b2f4793c.png)

You are talking about the second example maybe.
![ss02](https://user-images.githubusercontent.com/4763469/111796865-f26ff080-890b-11eb-962e-0de0a1b4c57f.png)

Source codes of all examples were  embedded in HTML code of the page, then you can read those easily.
Find text `ex-020.html` in the HTML code, for getting source code of the second example.

**Comment by lucaslgr** [comment]
I found it with your advice, thanks so much again @anseki

**Comment by anseki** [comment]
:smile:
