### ISSUE TITLE
browser compatibility 

### ISSUE THREAD

**Issue by Bokay6000** [anseki/plain-draggable#76]
Hey @anseki,
I'm using your library for a project and would like to know if it is compatible with the latest version of every modern browser?
Unfortunately I can not check for myself. 
I didn't find anything regarding support for different browsers on your website. 
Thanks for your help in advance!

PS: I'm also using LeaderLine, for which I would have the same question.

**Comment by anseki** [comment]
Hi @Bokay6000, thank you for the comment.
As described in the [document](https://anseki.github.io/plain-draggable/), modern web browsers are supported. Web browsers that don't meet the W3C web standards (e.g. IE10) are not supported.

**Comment by Bokay6000** [comment]
Thank you for your help!

**Comment by anseki** [comment]
:smile:
