### ISSUE TITLE
Drag Leader line from one div to another div

### ISSUE THREAD

**Issue by rruichava** [anseki/plain-draggable#77]
Hi,
I am using your libraries (Leaderline & plain-dragable) are very nice. I have a small issue when drag the Leader line from one div to another div it's not going to target div. it's stop the source div area part. Can you please help on this. Thanks.

**Comment by anseki** [comment]
Hi @rruichava, thank you for the comment.
Sorry, could you explain more?
What does “drag the Leader line” mean?
Do you mean that you want to drag the LeaderLine instead of `<div>` element?

**Comment by rruichava** [comment]
Hi @anseki, Thanks for reply back to me. I am using this [https://jsfiddle.net/3tn2bLer/1/](url) for drag and drop the Leaderline but I changed to html code like this `<div>
<div id="target-1" class="target"></div>
<div id="target-2" class="target"></div>
</div>
<div>
<div id="handle-start" class="handle"></div>
<div id="handle-end" class="handle"></div>
</div>`. After run and drag the line is not moving to the out of parent div.

**Comment by anseki** [comment]
Try this: https://jsfiddle.net/k290usLt/
See document: https://anseki.github.io/plain-draggable/#options-containment

**Comment by rruichava** [comment]
Thanks @anseki, it's working awesome

**Comment by anseki** [comment]
:smile:

**Comment by rruichava** [comment]
Hi @anseki, Thanks for helping [https://jsfiddle.net/k290usLt/](url) is it possible to disable or stop the draggable line when snapped is true?

**Comment by anseki** [comment]
Could you make new issue for another topic?
