### ISSUE TITLE
How to disable dragable line when snapped happend

### ISSUE THREAD

**Issue by rruichava** [anseki/plain-draggable#79]
Hi @anseki , Thanks for this library is there any way to disable or stop the draggable leader-line when snapped is true? [https://jsfiddle.net/3tn2bLer/1/](url)

**Comment by anseki** [comment]
Hi @rruichava, thank you for the comment.
You can use [`disabled`](https://anseki.github.io/plain-draggable/#disabled) property or [`remove`](https://anseki.github.io/plain-draggable/#remove) method.
It is unrelated to the LeaderLine.
See document: https://anseki.github.io/plain-draggable/
