### ISSUE TITLE
Issue with Leaderline plugin, multiple elements linked to one node becomes not movable except the last added one

### ISSUE THREAD

**Issue by guirama** [anseki/plain-draggable#8]
Hi,

First of all I would like to appreciate your invaluable creations of these two wonderful plugins plainDraggable and LeaderLine.

I am working on implementing a tree based structure starting from a single parent node in top. Top most parent can have multiple child nodes and users can dynamically add child nodes. Child nodes can also become parent nodes and tree can grow downward. All nodes are needed to be draggable9i used plainDraggable) and connected to their parents with LeaderLine.

The issue I came accross is, for a a parent node i can add first child node, it comes with LeaderLine and also movable.Then if I add the second child for same parent,second child comes with LeaderLine and also movable. But first one becomes not draggable. After 3rd one added its movable, 2nd one becomes immovable. Sorry if I have messed up it and if its not an issue with couple of plugins. 

I don't see any error in console as well.
`
        if($('#row_'+child_row).length)
        {

        }
        else
        {
            rows.push('row_'+child_row);
            rows['row_'+child_row] = new Array();
            elems['row_'+child_row] = new Array();
            $('#rowContainer').html($('#rowContainer').html()+'<div id="row_'+child_row+'"class="row padding0 mx-auto" style="margin:0 auto;"></div>');
        }

        if(type == 'greeting')
        {
            //alert(get_num_elements_of_row('row_'+child_row)); 
            var cindex = get_num_elements_of_row('row_'+child_row)+1;
            $('#row_'+child_row).html($('#row_'+child_row).html()+'<div class="col-1 padding0 text-center cnodewrapper"><i class="fa fa-handshake fa-3x greeting cnode nodes" id="e_'+child_row+'_'+cindex+'"></i></div>');
            elems['row_'+child_row].push('e_'+child_row+'_'+cindex);

            drags['e_'+child_row+'_'+cindex] = new PlainDraggable(document.getElementById('e_'+child_row+'_'+cindex));

            lines['e_'+child_row+'_'+cindex] = new LeaderLine(
                document.getElementById(parentNode),
                document.getElementById('e_'+child_row+'_'+cindex)
              );

            drags['e_'+child_row+'_'+cindex].containment = {left: 0, top: 0, width: '100%', height: '100%'};
            drags['e_'+child_row+'_'+cindex].onDrag = function(newPosition) {
            lines['e_'+child_row+'_'+cindex].position(); 

           /* $('.cnode').each(function(index,item){
                var thisId = $(this).attr('id');
                drags[thisId].position();
                lines[thisId].position();
            }); */
          };
        }
`

``

**Comment by guirama** [comment]
sure will do. Thanks

**Comment by guirama** [comment]
Hi,

I have added it on a jsfiddle , please follow the  steps given in below to see the issue.

[http://jsfiddle.net/ez5q7nwj/25/](http://jsfiddle.net/ez5q7nwj/25/)

1.Right Click on Play button below
2.Select Add Greeting node
3.A child node will appear (lets call its "node A"), right click on it and again select "Add Greeting Node"
4.A child node will appear(lets call its "node A1") with leaderline and movabale
5.Right clickaa2 on "Node A" and again select "Add Greeting Node" to add "Node A2"
6.Node A2 is movable, no issue
7.But Node A1 is no longer movable
Only the node added last is movable, others become not movable

**Comment by anseki** [comment]
I see.
This is very simple bug in your code.
I fixed your example.
See: http://jsfiddle.net/ez5q7nwj/33/

This is because of DOM specifications, it has nothing to do with PlainDraggable.
You replaced HTML code of elements with new one. For example this line:

```js
$('#rowContainer').html($('#rowContainer').html()+'<div...></div>');
```

Therefore, all elements in the `#rowContainer` tree were cleared, and new DOM tree instance was constructed completely even if the same HTML code. That is, those elements are not original elements now, and all event listeners, properties, and others also were cleared. The event listeners for PlainDraggable also are cleared. Of course those of other than PlainDraggable too. This means that all libraries may not work, not only PlainDraggable.

You should use `append` method instead:

```js
$('#rowContainer').append('<div...></div>');
```

**Comment by guirama** [comment]
Thanks a lot for pointing it out . Once again thanks a lot for creating
these very cool plugins.

Best Regards

Indunil

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you close this issue because it was solved?

**Comment by guirama** [comment]
Yes, your advise solved in perfectly and in one shot. :) .I ll close it,
