### ISSUE TITLE
how to delete the plaindraggable using thier ID's, 

### ISSUE THREAD

**Issue by roopali471** [anseki/plain-draggable#80]
i'm trying to remove the plaindraggable on click of element, but it was deleting last element's plainDraggable , Is it possible to delete based on Id

**Comment by anseki** [comment]
Hi @roopali471, thank you for the comment.
Could you explain more?
What does “ID” mean?
Could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by roopali471** [comment]
ID meaning plaindraggable creating a unique ID's on each element like 1 2 3 using that uniqueID is it possible to do draggable.remove( ). Because draggable.remove is deleting the last instance

**Comment by anseki** [comment]
ID is unneeded for removing an instance because `remove()` method removes only specific instance (not last instance).
See document: https://anseki.github.io/plain-draggable/#remove
For example:
```js
const instance1 = new PlainDraggable(element1),
  instance2 = new PlainDraggable(element2);

instance1.remove() // instance1 is removed
instance2.remove() // instance2 is removed
```

**Comment by anseki** [comment]
For example: https://jsfiddle.net/bg2t8eda/

**Comment by roopali471** [comment]
Ok got it, Thank you so much  for your time and solution

**Comment by anseki** [comment]
:smile:
