### ISSUE TITLE
The content of the element will become blurred after dragging

### ISSUE THREAD

**Issue by meteorlin** [anseki/plain-draggable#81]
Great project!
In the process of using it, I found that when dragging a larger div, its content will become blurred. Is there any solution?
Thanks in advance!
* In the picture below, the blue part on the left is the normally displayed element, and the window-like element on the right is the drag element.
![image](https://user-images.githubusercontent.com/49402403/117234129-f96ca700-ae56-11eb-9d34-044038f6c99b.png)

**Comment by anseki** [comment]
Hi @meteorlin, thank you for the comment.
To reproduce that, could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by meteorlin** [comment]
Thanks for your quick reply!
I developed the project under the framework of Vue3. I initialize the child component by creating a new component in the root Vue component and register it in plain-draggable.
The following is an example of my implementation in `codesandbox` ([example](https://codesandbox.io/embed/vue-composition-api-example-forked-vqtr9?fontsize=14&hidenavigation=1&theme=dark)). Click the button `click me to insert a plain` to create a draggable element (the drag handle is the green part).
You may need to move back and forth a few times to see that the text in the moved element is blurred.
![image](https://user-images.githubusercontent.com/49402403/117243772-6d647a80-ae6a-11eb-948d-37dc8620c506.png)

**Comment by anseki** [comment]
I tried your example with Blink, Gecko and Trident, then it seems that the issue was not reproduced (in Trident, the example didn't work).
Your GPU driver might have a problem. Or, it might be caused by web browser, version of the web browser, OS, version of the OS or GPU.
Anyway, sorry that we can do nothing because the issue can't be reproduced.

**Comment by meteorlin** [comment]
Thank you again! I still don't know what went wrong, and it does not happen when I run it on other devices (including mobile phones). Now there is a situation where a button is rendered into two parts (half clear and half blurred)...
![image](https://user-images.githubusercontent.com/49402403/117261763-1ae38800-ae83-11eb-900f-b3619d73830f.png)

**Comment by anseki** [comment]
This is caused by your GPU driver maybe.
The library uses `translate` CSS function that works with GPU.
Then, it might be solved by adjusting "hardware acceleration" configration of your web browser, "font-smoothing", etc.

**Comment by meteorlin** [comment]
Hi @anseki, I found that after setting the "will-change" property to "unset!important", the "blurred" disappeared, but there was a slight lag, which seems acceptable at present.
In addition, the "pixelated" mentioned in question #38 may be what I call "blurry".

**Comment by anseki** [comment]
Thank you for the information.
Yes, as I said, this is caused by your GPU driver. The `will-change` makes it work with GPU.
Then, it might be solved by adjusting "hardware acceleration" configuration of your web browser or your GPU driver.
