### ISSUE TITLE
With CSS `scale`

### ISSUE THREAD

**Issue by namasher** [anseki/plain-draggable#87]
Hi nice job with this library. I'm facing an issue where the draggable element disappears from the container div. It changes the position when the div is scaled up or down. Do you know how I can prevent this from happening and that the draggable elements inside the div keeps working after a new scale is applied? Thanks!

**Comment by anseki** [comment]
Hi @namasher, thank you for the comment.
To reproduce that, could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by namasher** [comment]
Hi @anseki thank you for the fast answer. I made this example: https://jsfiddle.net/8k0wd4jy/10/

If I change the scale of the container on the CSS the draggable elements starts to miss behave it will go outside the container boundaries, the pointer is lost and it can even dissapear, hope my example is useful to understand my issue. Thanks!

**Comment by anseki** [comment]
This may help you: https://github.com/anseki/plain-draggable/issues/13

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
