### ISSUE TITLE
Dragging between containers

### ISSUE THREAD

**Issue by 625alex** [anseki/plain-draggable#9]
Good day,

Congratulations! This is some amazing work done on this plugin.

Would you be so kind to provide an example of dragging items between containers?

Thanks in advance.

**Comment by anseki** [comment]
Hi @625alex, thank you for the comment.
So, what is the container? Is that an element that is specified as [`containment`](https://anseki.github.io/plain-draggable/#options-containment) option?
Could you explain more about this issue?

**Comment by anseki** [comment]
No reply came, and I close this issue.

**Comment by anseki** [comment]
The `containment` option is used for avoiding that the draggable element is moved to outside of specific area.
Do you mean that you want to avoid that the draggable element is positioned at points other than specific points ?
For example, try to move the red element to the crossline or outside of the blue box:
https://anseki.github.io/plain-draggable/#ex-060-stage

**Comment by 625alex** [comment]
I want to move draggable element from Box A to Box B.

I guess the `containment` should wrap both Box A and Box B and the boxes should be Snap Targets. 
Is this correct?

**Comment by 625alex** [comment]
Correct, I want it to be positioned only within the boxes.

**Comment by anseki** [comment]
You can adjust dropped position of the draggable element by using [`onDragEnd`](https://anseki.github.io/plain-draggable/#options-ondragend).
For example:
https://jsfiddle.net/Lejqoz8p/

**Comment by 625alex** [comment]
This is fantastic! Thank you for your work and help!

**Comment by anseki** [comment]
I'm glad if I could help you. :smile:
