### ISSUE TITLE
There is a way to use PlainDraggable for an element without erase the current style of the element?

### ISSUE THREAD

**Issue by lucaslgr** [anseki/plain-draggable#90]
Hi @anseki , here I'm again :D

I've set my element in a plainDraggable but after that in some moment I need to rotate this element using `transform: rotate(90deg)` for exemple, I can do that without erase the current style that the plainDraggable lib has set on the element, but when I move the element again the element lost the transform: rotate(90deg).

There is some way to avoid this ?

**Comment by lucaslgr** [comment]
I've done this example, but I don't understand on my project when I move the element after rotate it the element come back without rotate.

https://jsfiddle.net/lucaslgr/4ckm7y0a/25/

**Comment by anseki** [comment]
Hi @lucaslgr, thank you for the comment.
I tried your example.
That seems to work fine. Do you mean that you can't drag the element after double clicking?

**Comment by lucaslgr** [comment]
No, I mean that after I rotate the element and I try to drag again the element style is reset by plainDraggable, but I don't understand why it's happing only in my vue project.

In the example above this works fine.

**Comment by anseki** [comment]
I see.
You can specify `leftTop` option. Better way for performance is separating the element.
For example: https://jsfiddle.net/t3y5da2o/
You might customize this for `containment` if you use.

**Comment by lucaslgr** [comment]
Hi @anseki, separate the element worked great for me! Thanks again!
Could you explain me why is best for performance? I'm a beginner in this concepts

**Comment by anseki** [comment]
When the `leftTop` option is not specified, the PlainDraggable tries to move the element by using the `translate` CSS function.
https://anseki.github.io/plain-draggable/#lefttop-option
If the `translate` CSS function is called, web browser tries to render the page by using GPU (hardware acceleration) instead of CPU.
https://www.google.com/search?q=css+gpu+performance
If you will show animation, enabling GPU is better.

**Comment by lucaslgr** [comment]
Thanks a lot @anseki ! It is truthfully interesting! I didn't know that.

**Comment by anseki** [comment]
:smile:
