### ISSUE TITLE
Setting a snap point relative to a draggable object

### ISSUE THREAD

**Issue by tawjaw** [anseki/plain-draggable#93]
Hello, 

Great library! 

How can I set the snap points relative to a draggable object position instead of fixed point? 

Thanks

**Comment by anseki** [comment]
Hi @tawjaw, thank you for the comment.
This may help you: https://jsfiddle.net/xv65wd1u/

**Comment by tawjaw** [comment]
@anseki Thanks!

So basically I can add onMove to the first draggable and update the snap to the second draggable. 

```js
addEventListener('load', () => {
  const draggable = new PlainDraggable(document.getElementById('drag1'));
  const draggable2 = new PlainDraggable(document.getElementById('drag2'));
  
  draggable.onMove = function(){
    draggable2.snap = {
        x: draggable.left + 160,
        y: draggable.top,
        base: 'document'
      };
  }

});
```

**Comment by tawjaw** [comment]
One more thing please, 

When the element is dragged, I want to move all the snapped elements to it with it. 
How can I do that? 

thanks

**Comment by anseki** [comment]
I'm glad if I could help you. :smile: 
Could you make new issue for another issue after close this issue?

**Comment by tawjaw** [comment]
@anseki Thanks! I'll start a new issue.
