### ISSUE TITLE
Error: This element is not accepted when parsing SVG Element

### ISSUE THREAD

**Issue by ishanuda** [anseki/plain-draggable#97]
Hi,

I am trying to parse an SVGRectangleElement to the lib but is not supported.
It gives the Error: This element is not accepted.

This is the element I am trying to parse into the library.

`
<rect id="rect_1" 
          class="ra-shape rect" 
          style="stroke: rgb(255, 0, 0); stroke-width: 1; stroke-opacity: 1; fill: rgb(175, 41, 76); fill-opacity: 1; pointer-events: all;">
</rect>`

NOTE: the element is in an inline SVG which resides on the iFrame element in an Angular project.

Setup:
1. Imported the library in the `angular.json` file after `npm i plain-draggable`.
2. In the component header declared the library type: 
`declare const PlainDraggable: any;`
3. Created The draggable:
`const draggable = new PlainDraggable(handle);`

plain-draggable v2.5.14
Angular v12.1.1
typescript v4.2.4

Thank you very much.

**Comment by anseki** [comment]
Hi @ishanuda, thank you for the comment.
Of course SVG is supported by the library.
For example: https://jsfiddle.net/7w2o1ed5/
Maybe your code failed to get the element. Check the value by e.g. `console.log(handle)`.

**Comment by ishanuda** [comment]
Hi,
Thank you for the example.
Yes, the element I commented on above is the `console,log` output. 
But I think it is because the element belongs to the SVG which is in the iFrame.
The library can not get to the element may be.

Still need to investigate what is going wrong with it.

However, when changing the XY attributes of the element using vanilla JS the element moves.
So that shows the element is having no issue.
Thank you very much.

**Comment by anseki** [comment]
Do you mean that the `console.log` printed the element? Also, did you write the `console.log` in the same place as `new PlainDraggable`?
If so, the issue is unrelated to `<iframe>` because the security-blocking affects the getting the element.
The `console.log` printed an element because the element was already got. If the getting the element was failed, the `console.log` never print the element.
Also, PlainDraggable never gets an element itself, therefore you have to pass an element to PlainDraggable. That is, something before `new PlainDraggable` has problem, and invalid argument was passed to PlainDraggable, then the error was thrown.

**Comment by ishanuda** [comment]
Hi, Thank you for the explanation.

Here is the code block that gives the error.
```

declare const PlainDraggable: any;

@Injectable()
export class ShapePainter implements OnDestroy {

  // ... more code
  private initShapeInteraction(): void {
    // .... more code
    const handle = this.shape.getDragHandle() as SVGElement;
    this.logger.debug('handle', handle); // <-- print the element and it is there (can manipulate with vanilla JS)
    const draggable = new PlainDraggable(handle); // <-- gives the error
  }

}
```

NOTE: the shape is a class that is having the original rect element and the drag handle element (also a rect).
When the rectangle has a fill color the element itself is used for dragging.
When the rectangle is having only the stroke then there is a shadow element as a handle for dragging the element.

Thank you very much.

**Comment by anseki** [comment]
If PlainDraggable is loaded into other than a document that has target draggable element, load it in the target document.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
